### PR TITLE
feat: remove none type from val type

### LINKED ISSUE #2029: Remove None from ValType and support reading S33
## Motivation

According to the [wasm spec](https://webassembly.github.io/spec/core/binary/types.html#binary-valtype), None is not one of the `ValType`. However, in our current code, None is one of `ValType` with code `0x40`. I think the reason for including it in `ValType` is for the condition block type of instruction `block`, `loop` and `if` as in [block-type](https://webassembly.github.io/spec/core/binary/instructions.html#binary-blocktype), where after we include `None` in `ValType`, we seems to be able to make the instruction loader code easier. However, first, it makes our data structure inconsistent to the one in the spec, and second, it makes our code more complicated and unclean, since we have to check for the `None` case every time we use `ValType`.

Besides, in the [wasm spec](https://webassembly.github.io/spec/core/binary/types.html#binary-valtype), the value for type index is `s33`, but in our code, the type index is read as `s32`, which narrows the index range, and gets inconsistent to the spec.

## Details

We can do the following refactor:
* In `BlockType`, we may store `std::optional<ValType>` to indicate the none case, and modify the instruction loader accordingly.
* Remove `None` from the `ValType`
* Remove all the usage of `ValType::None`
* Remove the `AcceptNone` from the parameter list of `checkValTypeProposals`
* Support parsing `s33`.

### PR DESCRIPTION
**Pull request by little-willy**
This PR fixes #2029.

It is based on #2030, and currently include the change in #2030. Should be after #2030.

### CODE REVIEW

**Comment by q82419** [comment]
Please help to fix to pass the lint. Thanks.

**Comment by little-willy** [comment]
@q82419 I have fixed the lint and also the java and rust SDK. PTAL.

**Review by ibmibmibm — CHANGES_REQUESTED** [review]

**Review by q82419 — DISMISSED** [review]

**Comment by little-willy** [comment]
@q82419 @ibmibmibm Can we merge this PR now?

**Review by ibmibmibm — APPROVED** [review]

**Comment by hydai** [comment]
Hi @little-willy 
We can merge it now, however, I found that there are some conflicts so it's not able to click the merge button. Could you please rebase on your side?

**Comment by little-willy** [comment]
@hydai Seems there is no more conflict after the main branch is merged.

**Comment by hydai** [comment]
Hi @little-willy 

I have no idea, but GitHub doesn't allow me to merge your PR.
截圖 2022-11-17 at 23 27 27@2x

**Comment by little-willy** [comment]
@hydai I have no idea where does this IWYU checker come from. The error message in the CI seems wired, and I cannot find any code related to the error message. Do you have any idea?

**Comment by little-willy** [comment]
On my side, it looks like 
image

**Comment by hydai** [comment]
The IWYU checker will not block the merge button. We will have another PR to fix it.
Could you try to rebase to the latest master again and do the force push? This is pretty strange.

**Comment by little-willy** [comment]
It's quite wired. When I merge the master branch, it shows `Everything up to date`, but when I try to rebase master, it shows conflict. I have rebased it, and there should not be any more conflicts. But I will need one more approval to get the PR merged.

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Thanks @little-willy

**Pull request merged**
