### PR TITLE
[Utils] Installer CI: Change debug option

### PR DESCRIPTION
**Pull request by SAtacker**
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Review by hydai — DISMISSED** [review]

**Comment by SAtacker** [comment]
`which` does not exist on Cent OS

**Comment by SAtacker** [comment]
And GitHub has blocked access to /usr/lib
```
 ls: cannot access '/usr/lib/wasmedge/': No such file or directory
Fail: Plugins not found
Error: Process completed with exit code 1.
```

**Comment by hydai** [comment]
Sounds like the `which` command is an issue.

**Comment by hydai** [comment]
> And GitHub has blocked access to /usr/lib
> 
> ```
>  ls: cannot access '/usr/lib/wasmedge/': No such file or directory
> Fail: Plugins not found
> Error: Process completed with exit code 1.
> ```

Do you know any documents about this rule? If we use a docker image why the GitHub runner can block this access?

**Comment by hydai** [comment]
Also, we may need to have a check for the `which` command. If the environment is not found, we should warn users.

https://stackoverflow.com/questions/70417033/bash-script-error-which-command-not-found

**Comment by SAtacker** [comment]
> Also, we may need to have a check for the `which` command. If the environment is not found, we should warn users.
> 
> https://stackoverflow.com/questions/70417033/bash-script-error-which-command-not-found

Yes, on it

**Review by hydai — APPROVED** [review]

**Pull request merged**
