### PR TITLE
Fix java code examples in README

### LINKED ISSUE #3091: bug: Outdated README in java bindings
### Summary

Code examples in bindings/java/README.md are out of date

### Current State

The class names (due to #2149) and some method signatures in the example section are out of date

### Expected State

Code example to match current code. I will submit a PR with updates

### Reproduction steps

Compile the code examples

### Screenshots

DESCRIPTION

### Any logs you want to share for showing the specific issue

_No response_

### Components

Others

### WasmEdge Version or Commit you used

f576ba7a2ef4678d4b371cd12242a866b13dae87

### Operating system information

Ubuntu 22.04

### Hardware Architecture

x86_64

### Compiler flags and options

_No response_

### PR DESCRIPTION
**Pull request by MichaelMorrisEst**
Fixes #3091

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by dannypsnl** [comment]
It seems before this you need to fix the binding.

**Comment by alabulei1** [comment]
Hi @MichaelMorrisEst ,

Can you please check out the CI tests? Thanks.

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Hi @MichaelMorrisEst 
Please rebase to the latest master, GitHub doesn't allow me to merge this PR.

CleanShot 2024-06-05 at 03 33 30

**Comment by MichaelMorrisEst** [comment]
Hi @hydai 
PR is now rebased

**Review by dannypsnl — APPROVED** [review]

**Comment by dannypsnl** [comment]
Oops, we don't use merge, try rebase or cherry-pick again.

**Comment by hydai** [comment]
Hi @MichaelMorrisEst 
I still cannot process the merge due to the following reason:

CleanShot 2024-06-05 at 11 38 55


It seems like the DCO check is not working. Could you please rebase and force-push the branch to trigger the DCO check again?

**Comment by MichaelMorrisEst** [comment]
Sorry, yes I did a merge rather than rebase. I have rebased now and force pushed, so hopefully all ok now

**Comment by hydai** [comment]
Hi @MichaelMorrisEst 
I just realized that the DCO bot is stuck due to an upstream issue.
A workaround PR is merged: https://github.com/WasmEdge/WasmEdge/pull/3451
Please rebase again to ensure the DCO check is working. Thanks.

**Comment by hydai** [comment]
Thanks @MichaelMorrisEst 👍

**Pull request merged**
