### PR TITLE
[Utils] Installer CI: Fix CI URL for python installer

### PR DESCRIPTION
**Pull request by SAtacker**
Change the dummy URL used for CI.

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Review by hydai — APPROVED** [review]

**Comment by SAtacker** [comment]
@hydai please take a note of the permission change from 644 to 755 to make the script executable.

**Comment by hydai** [comment]
Ah, that's fine in the previous one because we use ` | bash.` Or is this permission different from the previous install script?

**Comment by SAtacker** [comment]
> Ah, that's fine in the previous one because we use ` | bash.` Or is this permission different from the previous install script?

I think it's alright for shell/bash files to remain executable.

**Comment by hydai** [comment]
No problem. Let's merge this :-)

**Review by hydai — APPROVED** [review]

**Pull request merged**
