### PR TITLE
Translate install.md into simplified Chinese

### PR DESCRIPTION
**Pull request by jaredliw**

### CODE REVIEW

**Comment by hydai** [comment]
Hi @jaredliw 
Thanks for submitting this.

When you contribute code to WasmEdge, you are asked to sign a DCO (Developer Certificate of Origin) to ensure that the project has the proper rights to use your code. For the details, please refer to this page: https://www.secondstate.io/articles/dco/

Also, we already change the default tool from `wget` to `curl`. Please refer to this PR for more details: https://github.com/WasmEdge/WasmEdge/pull/970

**Comment by hydai** [comment]
Hi @jaredliw 
You may need to squash or rebase your old commits. Because the DCO requires every commit is signed.

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Looks fine. However, the DCO CI checker is not run. 
One possible reason is that you reopen this PR after you pushed it. Could you try to force push your branch again to trigger the checker?

**Comment by hydai** [comment]
Awesome. Thanks!

**Comment by jaredliw** [comment]
My pleasure <3

**Pull request merged**
