### PR TITLE
[Community] Nominate Shreyas Atre(@SAtacker) as WasmEdge Committers

### PR DESCRIPTION
**Pull request by hydai**
Dear WasmEdge Community,

It gives me great pleasure to nominate Mr. Shreyas Atre (@SAtacker) for the esteemed position of committer within our WasmEdge community. He has been instrumental in our work thus far, diligently serving as the primary reviewer and contributor for the Installer component. 

His exceptional contributions are evident in his development of the initial bash installer for WasmEdge, launched on September 6, 2021 (#376), followed by his creation of an improved Python installer, which went live on October 18, 2022 (#1914). His profound efforts have significantly eased the user experience by simplifying access to WasmEdge.

Therefore, I kindly invite the other maintainers to review this nomination and share their thoughts or approval. Your input is highly appreciated in ensuring a transparent and fair decision-making process.

Thank you for your time and consideration. 

Best regards,
hydai

References:
1. [Bash Installer Commit History](https://github.com/WasmEdge/WasmEdge/commits/master/utils/install.sh)
2. [Python Installer Commit History](https://github.com/WasmEdge/WasmEdge/commits/master/utils/install.py)

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by juntao — APPROVED** [review]
Looks great. Congratulations!

**Comment by dannypsnl** [comment]
+1

**Comment by dm4** [comment]
Nice! Thanks @hydai and @SAtacker !

**Comment by q82419** [comment]
+1

**Comment by alabulei1** [comment]
LGTM!

**Comment by ibmibmibm** [comment]
+1

**Pull request merged**
