### PR TITLE
[Feat] - Remove Old English and Chinese Docs

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Description:

This PR removes the old English and Chinese Docs

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by adithyaakrishna** [comment]
Keeping the theme and book.toml files as they are needed to set up the redirections

**Comment by hydai** [comment]
Hi @adithyaakrishna 
Since you are removing the English docs, I would like to know if the redirect is already set to the new docs site.

**Comment by adithyaakrishna** [comment]
Not yet. Actually, @alabulei1 wanted me to work on removing the docs first. I'm trying to setup the local instance of mdbooks but its just giving errors, so I wanted to be sure and test my changes before sending in the redirections

**Comment by adithyaakrishna** [comment]
Closing this PR as it is superseded by https://github.com/WasmEdge/WasmEdge/pull/2709

**Pull request closed without merging**
