### PR TITLE
[Bug] - Fixed Broken Link

### PR DESCRIPTION
**Pull request by adithyaakrishna**

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

### Commit 1
Key changes:
- A broken link in the documentation has been fixed.
- The second demo application's link has been updated to the correct URL.

Potential problems:
- There are no potential problems evident in this patch.

**Comment by DarumaDocker** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

**Comment by hydai** [comment]
Hi @alabulei1 
Please check if the new link is the correct one. Thanks.

**Comment by alabulei1** [comment]
This link works. Thanks @adithyaakrishna .

**Review by hydai — APPROVED** [review]

**Pull request merged**
