### PR TITLE
[DO NOT MERGE UNTIL VOTE] Add a new contact for reporting conduct issues

### PR DESCRIPTION
**Pull request by alabulei1**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

**Comment by hydai** [comment]
Please review and vote for this.
cc @juntao @q82419 @hydai @ibmibmibm

**Review by juntao — APPROVED** [review]

**Review by hydai — APPROVED** [review]
LGTM

**Review by ibmibmibm — APPROVED** [review]
LGTM

**Comment by hydai** [comment]
3/4 maintainers approved. Merging it.

**Pull request merged**
