### PR TITLE
Added .github/workflows/lint.yml

### LINKED ISSUE #3519: Create a workflow detect EOF and fix it for PR automatically
### Summary

Seems linelint[1] can help us to do this.

### Appendix

1. https://github.com/marketplace/actions/linelint

### PR DESCRIPTION
**Pull request by arujjval**
closes #3519

### CODE REVIEW

**Comment by hydai** [comment]
Please fix the DCO check.

**Comment by arujjval** [comment]
@hydai I have included the signed-off. Can you rerun the test?

**Review by 0yi0 — CHANGES_REQUESTED** [review]
The action mentioned in #3519 should be https://github.com/fernandrone/linelint, and please use a specific version instead of master, thanks.

**Comment by hydai** [comment]
@arujjval 
The DCO failed. Please check again. Your signature is wrong.

**Comment by arujjval** [comment]
Okay, I will make a new PR. I am closing this one.

**Pull request closed without merging**
