### PR TITLE
changing permission hierarchy in the workflows 

### PR DESCRIPTION
**Pull request by jaydee029**
For issue #2979

I re-read the [ossf scorecard documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and realized that in an ideal workflow the permissions at the top level shouldn't be anything more than ` contents:read ` or `read-all`. All the other permissions need to be specified at the job level.
I made the required changes in a few files.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by jaydee029** [comment]
@hydai any reason why test wasmedge core is failiing?

**Comment by hydai** [comment]
We should have a fix for it soon. Just figuring out the latest commits is related to this issue.

**Comment by jaydee029** [comment]
I think unwanted commits go added in this PR, I think I should raise a new one instead

**Pull request closed without merging**
