### PR TITLE
[Utils] Install Script Improvement

### PR DESCRIPTION
**Pull request by SAtacker**
* Behaviour: Creates Shell profiles/configuration files only if these pre-exist.
* Suggestions from https://github.com/WasmEdge/WasmEdge/issues/1058

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by SAtacker** [comment]
image

Cent OS 8: https://www.centos.org/centos-linux-eol/ 
Workarounds: https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist

**Comment by hydai** [comment]
Hi @SAtacker 
I would like to know which one is better?
The centos 8 is a testing environment and we don't use it for building wasmedge.
How about upgrade to centos 8 stream? Or centos 9?

**Comment by SAtacker** [comment]
> Hi @SAtacker 
> I would like to know which one is better?
> The centos 8 is a testing environment and we don't use it for building wasmedge.
> How about upgrade to centos 8 stream? Or centos 9?

As per their announcements they have shifted their focus on Cent Os stream. I think more people would use a supported OS. The Cent Os 8 Stream has 2 Years to EOL.

**Comment by hydai** [comment]
Great. Could you please update the CI Action to use CentOS 8 Stream instead of CentOS 8?

**Comment by SAtacker** [comment]
> Great. Could you please update the CI Action to use CentOS 8 Stream instead of CentOS 8?

Yes, :+1:

**Comment by SAtacker** [comment]
There are no official docker images for Stream

**Comment by hydai** [comment]
https://quay.io/repository/centos/centos?tag=latest&tab=tags

I found that there is no official image on dockerhub, but on the quay.io.

**Review by hydai — APPROVED** [review]

**Pull request merged**
