### PR TITLE
[WASI] Proposal wasi crypto

### PR DESCRIPTION
**Pull request by sonder-joker**
@hydai May I do something wrong out of host/wasi_crypto folder.
1. If I need move wasi-crypto to plugin?
2. If I do right thing on export wasi-crypto? I may have overused `WASMEDGE_BUILD_WASI_CRYPTO`.
3. I may need fix some github action.
4. rust sdk need sync?

### CODE REVIEW

**Comment by hydai** [comment]
> If I need move wasi-crypto to plugin?

We will have the first PR merged without converting wasi-crypto to a plugin. This will be done before we merge `proposal/wasi-crypto` to `master`. So it's fine currently. If you want to continue the plugin migration job, please let me know. Or I can take this forward if you don't :-)

> If I do right thing on export wasi-crypto? I may have overused WASMEDGE_BUILD_WASI_CRYPTO.

Not sure what does the `export` mean? This defined value is totally fine. Just like the WASI_NN one.
Ref: https://github.com/WasmEdge/WasmEdge/pull/973/files

> I may need fix some github action.

Could you list the failed actions? Maybe some of them are not related to your code directly.

> rust sdk need sync?

Please deal with this at the last step. You can find that the rust binding is reflecting the C API. In this case, please make sure the C API is working, then update the rust binding. I think there should be a simple rebase only?

**Comment by hydai** [comment]
Hi @sonder-joker 
I just switch the base branch from `master` to `proposal/wasi-crypto`. Could you please base on this branch? After you remove the unrelated commits, those commits are from others. Then, I will merge this directly.

**Comment by sonder-joker** [comment]
@hydai  It should work now :D

**Review by hydai — APPROVED** [review]
LGTM. Thanks for your contribution :-)

**Pull request merged**
