### PR TITLE
[Loader] Serializer: Finish GC type tests

### PR DESCRIPTION
**Pull request by elhewaty**
This PR adds the missing tests for https://github.com/WasmEdge/WasmEdge/pull/3821

Signed-off-by: Mohamed Atef <mohamedatef1698@gmail.com>

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by elhewaty** [comment]
@q82419, PTAL

**Review by q82419 — CHANGES_REQUESTED** [review]
Excellent.
Can you help to add the test about the struct type? Thanks!

**Comment by elhewaty** [comment]
Do you mean in a rectype or the standalone struct type?

If you mean the standalone struct type, there is a test added before.

**Comment by q82419** [comment]
> Do you mean in a rectype or the standalone struct type?
> 
> If you mean the standalone struct type, there is a test added before.

That was the value type.
I think the following tests can improve the coverage:

1. Test CompositeType (Array).
2. Test CompositeType (Struct).
3. Test CompositeType (Array) without GC proposal.
4. Test CompositeType (Struct) without GC proposal.

**Comment by q82419** [comment]
Additional information:
You can check the coverage report in the above link, and view into files.
For example:
https://app.codecov.io/gh/WasmEdge/WasmEdge/pull/3865/blob/lib/loader/serialize/serial_type.cpp

We won't expect that we reach 100% coverage in the WasmEdge project.
But we expect that we can cover the mainly functions to avoid hidden bugs.
That's why we need such much tests.

**Review by q82419 — APPROVED** [review]

**Pull request merged**
