### PR TITLE
[Misc] Removed binfmt support

### PR DESCRIPTION
**Pull request by hydai**
Signed-off-by: hydai <hydai@secondstate.io>

The binfmt related tools are no longer using. It's a good time to remove it from our source tree.

### CODE REVIEW

**Review by ibmibmibm — DISMISSED** [review]

**Comment by ibmibmibm** [comment]
`s/deprecated/removed/`

**Comment by hydai** [comment]
@ibmibmibm  Updated.

**Review by ibmibmibm — APPROVED** [review]

**Comment by vt-alt** [comment]
Why binfmt support is removed? Was it insecure or something?

**Comment by hydai** [comment]
Hi @vt-alt 
The only reason is that we are shifting the focus to the Crun integration [1]. Due to limited engineering resources at that time, we were unable to maintain binfmt support and decided to drop it until someone expressed interest in this feature. It has been a long time (from 2021 to 2025), and you are the only person who has asked us about it. ;-).

[1]: https://github.com/second-state/crunw/commit/060b2755b97d5affd2576ce10f7a1e42b08292c6

**Pull request merged**
