### PR TITLE
[MISC] Add missing suffixes for string view literals

### PR DESCRIPTION
**Pull request by jeongkyu**

### CODE REVIEW

**Review by hydai — DISMISSED** [review]
Nice catch.

**Comment by hydai** [comment]
Hi @jeongkyu 
I found that your commit is not DCO signed. Could you please sign your commit with `--signoff`.

**Comment by jeongkyu** [comment]
Hi @hydai 
Thanks for pointing it out.
I signed off my commit and pushed it again.

**Review by hydai — APPROVED** [review]
LGTM. I am merging this after the CI is green.

**Pull request merged**
