### PR TITLE
[Docs] Update security-related files

### PR DESCRIPTION
**Pull request by dm4**
This pull request updates the security-related files according to the [CNCF tag-security templates](https://github.com/cncf/tag-security/tree/main/project-resources), including `SECURITY.md`, `docs/SECURITY_CONTACTS.md`, and `docs/embargo-policy.md`. However, we still have some items to be decided:

#### `SECURITY.md`
- [x] We need to decide on a channel or mailing list for announcing security information.
  - Use <wasmedge@googlegroup.com>
- Should we change <security@secondstate.io> to another mailing list that is owned and run by community participants?
  - Use <wasmedge-security@lists.cncf.io>
    - [x] Need to set it up.
- [x] Determine the disclosure timeline.
  - We follow a 90 days disclosure timeline to ensure we provide a quality, tested release.
- [x] Decide on supported versions.
  - Current `0.13.5`, `0.14.0`.

#### `SECURITY_CONTACTS.md`
- [x] Decide on the security contacts for WasmEdge.
  - @hydai, @ibmibmibm, @dm4
- [x] Document this decision process in our `GOVERNANCE.md`.
  - The **Security Response Team** section is already in our `GOVERNANCE.md`.

#### `embargo-policy.md`
- [x] Determine the disclosure timeline (same as mentioned in `SECURITY.md`).

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
I  think the mailing list for receiving security reports should be a private email list. Then, we will have a specific email address to respond to the report email.

**Comment by hydai** [comment]
> I think the mailing list for receiving security reports should be a private email list. Then, we will have a specific email address to respond to the report email.

If possible, let's use security@wasmedge.org. We could have this set up via the CNCF service deck, right?

**Comment by alabulei1** [comment]
> > I think the mailing list for receiving security reports should be a private email list. Then, we will have a specific email address to respond to the report email.
> 
> If possible, let's use [security@wasmedge.org](mailto:security@wasmedge.org). We could have this set up via the CNCF service deck, right?

Yes, please.

**Comment by dm4** [comment]
We need to decide on the security contacts to list in `SECURITY_CONTRACTS.md` and document the decision-making process in `GOVERNANCE.md`. This part may require discussion among the maintainers.

Users do not directly report vulnerabilities to the security contact but rather consult them when they have security-related questions.

Please refer to the following explanation:

```
# Security Contacts

Defined below are the security persons of contact for WasmEdge. If you have
questions regarding the triaging and handling of incoming problems, they may be
contacted.

The following security contacts have agreed to abide by the [Embargo Policy](./embargo-policy.md)
and will be removed and replaced if found to be in violation of that agreement.

DO NOT REPORT SECURITY VULNERABILITIES DIRECTLY TO THESE NAMES, USE THE
INSTRUCTIONS AT OUR [SECURITY POLICY](../SECURITY.md).
```

**Comment by hydai** [comment]
For the security contacts, I think @dm4, @ibmibmibm, and me(@hydai) should be the initial members.

cc @juntao WDYT?

**Comment by hydai** [comment]
@alabulei1 We updated all related entries, PTAL

Hi, @WasmEdge/maintainers 

Please vote if you agree with the new security policy
cc @juntao @ibmibmibm @q82419 @hydai

**Comment by alabulei1** [comment]
LGTM

**Comment by q82419** [comment]
LGTM

**Comment by ibmibmibm** [comment]
LGTM

**Review by ibmibmibm — APPROVED** [review]

**Comment by hydai** [comment]
3/4 maintainers approved. Prepare to merge.

**Review by hydai — APPROVED** [review]
LGTM

**Pull request merged**
