### PR TITLE
[CMake] Add an option to enable undefined behavior sanitizer

### PR DESCRIPTION
**Pull request by hydai**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by q82419** [comment]
Should we enable UB sentilizer directly in debug mode?

**Review by q82419 — CHANGES_REQUESTED** [review]
Should add the docs.

**Comment by hydai** [comment]
@q82419 
The document is moved to a new repo. No need to add documents here anymore.

**Comment by q82419** [comment]
> @q82419 The document is moved to a new repo. No need to add documents here anymore.

I think we'd better to add the docs here before the Vivian's PR.
Or it'll hard to sync the docs.

**Comment by hydai** [comment]
I don't think so. The document way is changed. Why do we need to do the same thing twice?

**Review by q82419 — APPROVED** [review]

**Pull request merged**
