### PR TITLE
[Docs] Add installer guide

### LINKED ISSUE #2206: [Installer] Provide a spec file to describe the feature and behavior of the WasmEdge installer
## Motivation

We need a document to describe what features the installer should ship and how behavior the installer should do in various use cases. We should have a document to identify this information to clarify and reduce the maintenance cost.

## Details

1. Create a document called `installer guide`
2. Define the options and flags.
3. Describe the available use scenarios.

### PR DESCRIPTION
**Pull request by hydai**
Fixes #2206

### CODE REVIEW

**Comment by SAtacker** [comment]
Hi, sorry I forgot about this one. I'll review it by tomorrow EOD. Thanks!

**Review by SAtacker — APPROVED** [review]

**Comment by SAtacker** [comment]
Is there anything I can do to fix DCO?

**Comment by hydai** [comment]
It looks like the `GitHub squash` will change the committer. This is a false negative. The DCO should be handled by `GitHub`. However, it is not.

We have two ways to fix this:
1. Remake this branch.
2. Set the DCO pass. (Since it's a false negative. You already signed the DCO)

**Comment by hydai** [comment]
Ok, I just fixed this issue with a new PR #2223. Closing this.

**Pull request closed without merging**
