### PR TITLE
[utils] Fix https://github.com/WasmEdge/WasmEdge/issues/1501

### PR DESCRIPTION
**Pull request by SAtacker**
Installer Script: Tweak sort version sort for better semantic soring

* Fix https://github.com/WasmEdge/WasmEdge/issues/1501

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by SAtacker** [comment]
Consider the following cases:
```
satacker@ubuntu:~/wasm_work/WasmEdge$ printf %s\\n%s "0.9.1-beta.1" "0.9.1" | sort --version-sort
0.9.1
0.9.1-beta.1
satacker@ubuntu:~/wasm_work/WasmEdge$ printf %s\\n%s "0.9.1-beta.1" "0.9.2" | sort --version-sort
0.9.1-beta.1
0.9.2
satacker@ubuntu:~/wasm_work/WasmEdge$ printf %s\\n%s "0.9.1-beta.1" "0.9.1-rc.1" | sort --version-sort
0.9.1-beta.1
0.9.1-rc.1
satacker@ubuntu:~/wasm_work/WasmEdge$ printf %s\\n%s "0.9.1-rc.1" "0.9.1-beta.1" | sed '/-/!{s/$/_/}' | sort --version-sort | sed 's/_$//'
0.9.1-beta.1
0.9.1-rc.1
satacker@ubuntu:~/wasm_work/WasmEdge$ printf %s\\n%s "0.9.1-rc.1" "0.9.2" | sed '/-/!{s/$/_/}' | sort --version-sort | sed 's/_$//'
0.9.1-rc.1
0.9.2
satacker@ubuntu:~/wasm_work/WasmEdge$ printf %s\\n%s "0.9.1-rc.1" "0.9.1" | sed '/-/!{s/$/_/}' | sort --version-sort | sed 's/_$//'
0.9.1-rc.1
0.9.1
```

**Comment by SAtacker** [comment]
Used `awk '{ if ($1 ~ /-/) print; else print $0"_" ; }'` instead of `sed '/-/!{s/$/_/}'` to make it compatible on macOS

**Comment by hydai** [comment]
Maybe we can have the test case to cover this issue? Especially listing all special versions is better. We have several key points, e.g. supporting images/tf on aarch64, or macOS, enabling plugin support, and so on.

**Comment by SAtacker** [comment]
Please check, Thanks

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Awesome 😎 
Thanks.

**Pull request merged**
