### PR TITLE
Apply old WASM proposals.

### PR DESCRIPTION
**Pull request by q82419**

### CODE REVIEW

**Comment by yanganto** [comment]
Hi @q82419,
The rust binding will use the new path of the `wasmedge.h`.
And there are some header files not there, may you help me to locate these headers.
Thanks.
```text
  32 #include "wasmedge/enum_configure.h"
  33 #include "wasmedge/enum_errcode.h"
  34 #include "wasmedge/enum_types.h"
```

**Comment by yanganto** [comment]
Hi @q82419 

Where is `wasmedge.h` If CI follows the original flow to use the header files after build and before install?
The header files are not listed in `build/include/api/wasmedge`.
May you help to locate the header files after build and before install?

**Comment by q82419** [comment]
You can add the followings:
```
configure_file(api/wasmedge/int128.h api/wasmedge/int128.h COPYONLY)
configure_file(api/wasmedge/wasmedge.h api/wasmedge/wasmedge.h COPYONLY)
```
Into the `include/CMakeLists.txt` to copy the headers into the build folder.

**Review by hydai — CHANGES_REQUESTED** [review]
Because this PR contains breaking changes, you should add these information in CHANGELOG in the same PR.

**Comment by q82419** [comment]
This PR should be merged after the 0.8.3 release.

**Review by hydai — APPROVED** [review]

**Pull request merged**
