### PR TITLE
[Bug] - Remove Checkbox in Release Process Docs and Update Installer Docs

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

The release process docs have a checkbox after the bullet point in the list. Please refer to the SS below regarding the same. This PR removes the checkboxes at the start of the list.

Screenshot 2023-04-19 at 1 10 43 PM

Also, there is no way to determine the note when a user lands on this page as it looks similar to the text on the site. Hence this PR makes the Notes heading bold such that visitors can easily differentiate between it.

Screenshot 2023-04-19 at 1 13 22 PM

### CODE REVIEW

**Comment by DarumaDocker** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

**Comment by alabulei1** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

**Comment by hydai** [comment]
Hi @adithyaakrishna 
The release process file is a template for us to use in each release, which means that we will copy it and use the checkbox functions. So it's fine to keep them. Thanks.

**Comment by hydai** [comment]
You can use this PR and revert that change. I will merge it with squashing.

**Comment by hydai** [comment]
Hi @adithyaakrishna 
Do you want to update this PR?

**Comment by adithyaakrishna** [comment]
@hydai Thank you for reminding me about this, I had missed this one, I have updated the PR with the above commit :)

**Review by hydai — APPROVED** [review]
Thanks!

**Pull request merged**
