### PR TITLE
[Utils] Install Script Fix

### PR DESCRIPTION
**Pull request by SAtacker**
* Removed dangerous removal of path #412 
* Quoting of variables as per shellcheck 2086
https://github.com/koalaman/shellcheck/wiki/SC2086.
* Apologies to the affected users ;-(

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by SAtacker** [comment]
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_install_script/utils/install.sh | bash -s -- -e all
```
I have removed the dangerous part so you can test it. Please let me know.

**Comment by juntao** [comment]
I found that if I have `sudo` installed and install wasmedge into `~/.wasmedge`, the script will NOT write the `source env` command into `.profile` or `.bashrc`

**Comment by SAtacker** [comment]
> I found that if I have `sudo` installed and install wasmedge into `~/.wasmedge`, the script will NOT write the `source env` command into `.profile` or `.bashrc`

If they give the path manually then I don't write an `env` file because then I'll have to populate their custom directory

**Comment by SAtacker** [comment]
A bit sad news `"API rate limit exceeded for 111.125.230.183. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"`. This means I cannot use GitHub's API anymore, we may get more than 1000 a day and nobody else would be able to install like I am facing right now.

**Comment by juntao** [comment]
> If they give the path manually then I don't write an `env` file because then I'll have to populate their custom directory

In my tests, I did not give a path. It installs into HOME/.wasmedge in both tests. However,

* test 1: the system does not have `sudo` and the install behaves correctly.
* test 2: the system has `sudo` and the script did not add the `source env` commands in bash profile files.

**Comment by juntao** [comment]
> A bit sad news `"API rate limit exceeded for 111.125.230.183. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"`. This means I cannot use GitHub's API anymore, we may get more than 60 an hour and nobody else would be able to install like I am facing right now.

I think the rate limiting is based on IP address? That means the user will not have this problem since they will each have a different IP address. Correct?

**Comment by SAtacker** [comment]
> > If they give the path manually then I don't write an `env` file because then I'll have to populate their custom directory
> 
> In my tests, I did not give a path. It installs into HOME/.wasmedge in both tests. However,
> 
>     * test 1: the system does not have `sudo` and the install behaves correctly.
> 
>     * test 2: the system has `sudo` and the script did not add the `source env` commands in bash profile files.

Could you please confirm if this was after https://github.com/SAtacker/WasmEdge/commit/3d7cfd863a14ced06a758b0e372637262ae715a6?

**Comment by SAtacker** [comment]
> > A bit sad news `"API rate limit exceeded for 111.125.230.183. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"`. This means I cannot use GitHub's API anymore, we may get more than 60 an hour and nobody else would be able to install like I am facing right now.
> 
> I think the rate limiting is based on IP address? That means the user will not have this problem since they will each have a different IP address. Correct?

I have added https://github.com/SAtacker/WasmEdge/commit/442bc1e277cce2de0f67f8067975e6829e6a336c which removes the GitHub API dependency. I'll have to check on MacOs once if it works (If all the standard tools are present there as well or not)

**Comment by SAtacker** [comment]
It does not work on macOS

**Comment by SAtacker** [comment]
Summar / Changelog
- [Utils] Minor Fix. [Shreyas Atre]

  * __HOME___ was echoed instead of HOME
  * If .profile does not exists, it is created
- [Utils] Fix for macOS. [Shreyas Atre]

  * Apparently macOS cut & tail don'r have long options same as popular
  linux distros.
- [Utils] Remove github API request. [Shreyas Atre]

  * This removes the limitations of GitHub API request using git and
  standard tools itself.
- [Utils] Don't mess with $HOME value. [Shreyas Atre]

  * Introduced __HOME__ and checked if getent is giving empty values.
  * If it is an empty string __HOME__ will be same as HOME
- [Utils] Add to .bashrc & .profile. [Shreyas Atre]

  * Changed previous behaviour of appending to any one of above to both
  the above.
- [Utils] Add sourcing to .bashrc as well. [Shreyas Atre]

  * Added suggestions as per https://github.com/WasmEdge/WasmEdge/issues/415#issue-996302490
- [Utils] Install Script Fix. [Shreyas Atre]

  * Removed dangerous removal of path
  * Quoting of variables as per shellcheck 2086
  https://github.com/koalaman/shellcheck/wiki/SC2086.

**Comment by juntao** [comment]
If I do 

```
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_install_script/utils/install.sh | bash -s -- -e all -p /usr/local
```

It will have the following line in `.profile` and `.bashrc`

```
. "/usr/local/env"
```

The content of the `/usr/local/env` is as follows.

```
#!/bin/sh
# wasmedge shell setup
# affix colons on either side of $PATH to simplify matching
case :${PATH}: in
    *:/root/.wasmedge/bin:*)
        ;;
    *)
        # Prepending path in case a system-installed wasmedge needs to be overridden
        export PATH=/root/.wasmedge/bin:$PATH
        ;;
esac
case :${LD_LIBRARY_PATH}: in
    *:/root/.wasmedge/lib:*)
        ;;
    *)
        # Prepending path in case a system-installed wasmedge libs needs to be overridden
        export LD_LIBRARY_PATH=/root/.wasmedge/lib:$LD_LIBRARY_PATH
        ;;
esac
```

I think we need a rule to NOT add the `source env` command when the install path is `/usr/local`.

**Comment by juntao** [comment]
Hmm, how did you test on MacOS? I do not think our release has a MacOS binary build yet. :)

**Comment by SAtacker** [comment]
I meant a dry run. 😀

**Comment by SAtacker** [comment]
> If I do
> 
> ```
> wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_install_script/utils/install.sh | bash -s -- -e all -p /usr/local
> ```
> 
> It will have the following line in `.profile` and `.bashrc`
> 
> ```
> . "/usr/local/env"
> ```
> 
> The content of the `/usr/local/env` is as follows.
> 
> ```
> #!/bin/sh
> # wasmedge shell setup
> # affix colons on either side of $PATH to simplify matching
> case :${PATH}: in
>     *:/root/.wasmedge/bin:*)
>         ;;
>     *)
>         # Prepending path in case a system-installed wasmedge needs to be overridden
>         export PATH=/root/.wasmedge/bin:$PATH
>         ;;
> esac
> case :${LD_LIBRARY_PATH}: in
>     *:/root/.wasmedge/lib:*)
>         ;;
>     *)
>         # Prepending path in case a system-installed wasmedge libs needs to be overridden
>         export LD_LIBRARY_PATH=/root/.wasmedge/lib:$LD_LIBRARY_PATH
>         ;;
> esac
> ```
> 
> I think we need a rule to NOT add the `source env` command when the install path is `/usr/local`.

It checks if the PATH contains `/usr/local` and then populates
```bash
case :${PATH}: in
    *:/root/.wasmedge/bin:*)
        ;;
    *)
        # Prepending path in case a system-installed wasmedge needs to be overridden
        export PATH=/root/.wasmedge/bin:$PATH
        ;;
esac
```
Meaning that you should not see overpopulated `PATH` environment variable

**Comment by juntao** [comment]
hmm, I just thought it is unnecessary for the `/usr/local/env` file even if it does not actually affect the `PATH`. Is there an easy fix?

**Comment by SAtacker** [comment]
> hmm, I just thought it is unnecessary for the `/usr/local/env` file even if it does not actually affect the `PATH`. Is there an easy fix?

We can create an `env` under `XDG_CONFIG_HOME` which is a standard for most of the applications.
Ref: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by juntao** [comment]
Perhaps we could do the following

1 Always leave an env file in the installed directory.

2 The env file content should reference the actual installed directory. That is `/usr/local/env` should not have `/root/.wasmedge` path.

3 The `.profile` and `.bashrc` files should contain the source env command ONLY when the `-p` argument is absent. 

What do you think?

**Comment by SAtacker** [comment]
> Perhaps we could do the following
> 
> 1 Always leave an env file in the installed directory.
> 
> 2 The env file content should reference the actual installed directory. That is `/usr/local/env` should not have `/root/.wasmedge` path.
> 
> 3 The `.profile` and `.bashrc` files should contain the source env command ONLY when the `-p` argument is absent.
> 
> What do you think?

Thank you for this! I agree completely. Initially, I overlooked the `*:/root/.wasmedge/bin:*` part even of `/usr/local` .
Sending a patch for all the mentioned suggestions.

**Review by juntao — APPROVED** [review]
I tested. It is read to merge now.

**Pull request merged**
