### PR TITLE
[WASI Socket] fix sock opt & add BINDTODEVICE

### PR DESCRIPTION
**Pull request by L-jasmine**
* fix `toSockOptSoName`
* add `BINDTODEVICE` for SetSockOpt & GetSockOpt

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by juntao** [comment]
flows review

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
The CI failed. I am checking the `polloneoff` part.

**Review by hydai — APPROVED** [review]

**Pull request merged**
