### PR TITLE
[Docs] fix various typo

### PR DESCRIPTION
**Pull request by RRobot-lm**
Signed-off-by: RRobot-lm <RRobot-lm@users.noreply.github.com>

### CODE REVIEW

**Comment by RRobot-lm** [comment]
Perhaps we can set up a linter like codespell or misspell to catch the typo automatically?

**Review by hydai — APPROVED** [review]
LGTM

**Comment by hydai** [comment]
> Perhaps we can set up a linter like codespell or misspell to catch the typo automatically?

Sounds good. Do you have any recommendations for these two tools? Or any other choices?

**Comment by RRobot-lm** [comment]
I would suggest using codespell. Although it has some false positives, it can be suppressed via `--ignore-words` file. The ability of misspell is limited.

Anyway, both tools have the option to fix typos automatically.

**Pull request merged**
