### PR TITLE
[Docs] Remove Unnecessary Docs and Reorganised Others

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- This PR removes unnecessary/unwanted docs from the books site.
- Reorganised other docs

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
@alabulei1 PTAL

**Comment by adithyaakrishna** [comment]
@hydai TIL - PTAL stands for Please take another look 🤯

**Comment by alabulei1** [comment]
Hi @adithyaakrishna 

Thank you for this PR. 

For this PR, we don't have special docs for Swift, AssemblyScript, and Kotlin, which doesn't mean that WasmEdge can't run programs in these languages. 

Again, the first priority is to migrate the content from the old doc and delete adding notes for the old docs. While the format of the old docs was nice, our main objective is to ensure that the WasmEdge/docs are synchronized with the old book. This is an essential aspect that we must focus on.  I have a document to keep track of what is updated or missing. Let me know if you have any questions. https://docs.google.com/document/d/1wYOLvhuWt50M0sMPGN2TlA5JMICzv5BSczPmV4GsilQ/edit?usp=sharing

**Comment by alabulei1** [comment]
@hydai  Are you ok with Moving `CODE_OF_CONDUCT.md`, `Ecosystem.md`, `GOVERNANCE.md`, and `OWNER.md`  from the docs directory to the project root?

**Comment by hydai** [comment]
Hi @adithyaakrishna 
I would like to know the intention of moving these files from the docs folder to the root folder. 
Also, replacing `*` with `-` doesn't make sense to me. It should be the same in the markdown. Is there any rule forbidding `*`?

**Comment by adithyaakrishna** [comment]
@alabulei1 Gotcha, could you pls lmk if I should revert any changes with respect to WasmEdge being able to  run programs in those languages?

@hydai I don't have any specific reason, if we decide to sunset `docs/` directory completely, then it would make much sense to move those files to the root directory. Also, regarding `-` and `*`, I thought to make them consistent across the whole project as we use `-` in some MD files, I updated them here as well 👀

**Comment by alabulei1** [comment]
Since the linting and moving `CODE_OF_CONDUCT.md`, `Ecosystem.md`, `GOVERNANCE.md`, and `OWNER.md` from the docs directory to the project root is not in a hurry, let's hold this PR before the migration is done.  Plus, the migration way will affect what the old book looks like.

cc @adithyaakrishna @hydai

**Comment by hydai** [comment]
1. IMO, I would like to keep these files inside the docs folder. Making it flatten into the root folder is unnecessary.
2. `*` and `-` are exactly the same. Humans should not modify it, or it should be on our checklist to make sure nobody will use another one. If we want to keep it in the same style, we should figure out how to use tools to fix it.

**Comment by adithyaakrishna** [comment]
@alabulei1 Okay sure, that makes sense :)

@hydai Actually prettier formats it to use `-` instead of `*`

**Pull request closed without merging**
