### PR TITLE
[Utils] Installer Improvements and Fixes

### PR DESCRIPTION
**Pull request by SAtacker**
- Reference: https://github.com/WasmEdge/WasmEdge/issues/2180

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by SAtacker** [comment]
The symbolic linking is dynamic and I don't see where to change the target filename.
Thanks! Please let me know if I miss out on something.
CC @q82419

**Comment by q82419** [comment]
A question is --
If I use the command `./install.sh -e all -v 0.12.0-alpha.1`, only the WasmEdge uses the assigned version, but the extensions use the `0.11.2` latest release version.
Is this behavior correctly?

cc @hydai

**Review by q82419 — APPROVED** [review]

**Comment by hydai** [comment]
> A question is -- If I use the command `./install.sh -e all -v 0.12.0-alpha.1`, only the WasmEdge uses the assigned version, but the extensions use the `0.11.2` latest release version. Is this behavior correctly?
> 
> cc @hydai

The corresponding extensions should have the same versions as the WasmEdge one if it is not specified.

**Comment by SAtacker** [comment]
Thanks for the reports @q82419 

Fixes:

1. https://github.com/WasmEdge/WasmEdge/issues/2180
2. https://github.com/WasmEdge/WasmEdge/issues/2186
3. https://github.com/WasmEdge/WasmEdge/issues/2187
4. https://github.com/WasmEdge/WasmEdge/issues/2188
5. https://github.com/WasmEdge/WasmEdge/issues/2190
6. https://github.com/WasmEdge/WasmEdge/issues/2191

**Review by hydai — APPROVED** [review]
@q82419 PTAL

**Comment by q82419** [comment]
LGTM

**Pull request merged**
