### PR TITLE
Remove the function address mechanism in the store

### PR DESCRIPTION
**Pull request by q82419**
The C API docs will be updated after the alpha stage.

### CODE REVIEW

**Comment by q82419** [comment]
@apepkuss , @yanganto 

Please note that after this PR merged, the API of the `FuncRef` changes.
You can choose to modify the rust side and add commits on this branch.
Thanks.

**Comment by apepkuss** [comment]
@q82419 I refactored the `wasmedge-sys` crate based on this branch to support the API changes (see PR #1361). The failed CI workflows related to `binding-rust` should work after merging PR #1361 into this branch. Could you please merge this PR after merging PR #1361 into this branch? Thanks a lot!

**Review by hydai — APPROVED** [review]

**Comment by q82419** [comment]
Hi @apepkuss ,

It seems the rust CI failed. Can you help to check the issue? thanks.

**Comment by apepkuss** [comment]
@q82419 This is a known issue that could be caused by a previous merge. I've already fixed it in PR #1358. I can launch a new PR with the same fix if it is necessary, is it? Thanks!

**Comment by q82419** [comment]
> @q82419 This is a known issue that could be caused by a previous merge. I've already fixed it in PR #1358. I can launch a new PR with the same fix if it is necessary, is it? Thanks!

Fix on that PR is ok. Thanks.

**Review by hydai — APPROVED** [review]

**Pull request merged**
