### PR TITLE
Fix large timestamp causing overflow

### LINKED ISSUE #3105: `fd_filestat_set_times` with a large timestamp leads to errno `inval`
### Summary

Calling `fd_filestat_set_times` with a large timestamp causes it to return errno 28 (inval).  In other runtimes, it succeeds.  Specifically, a large timestamp is something larger than int64 max like `13136941795642118959`.

Note that you cannot test this case using wasi-sdk's `futimens` because `struct timespec` only contains int64 `tv_sec`.

### Current State

_No response_

### Expected State

_No response_

### Reproduction steps

Run this WAT with wasmedge, mounting any directory.  It should exit without error. But with WasmEdge it exits with 28 (inval).

```wat
(module
  (type (func))
  (type (func (param i32 i64 i64 i32) (result i32)))
  (type (func (param i32)))
  (import "wasi_snapshot_preview1" "fd_filestat_set_times" (func $fd_filestat_set_times (type 1)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (type 2)))
  (func $_start
    (local $err i32)

    (call $fd_filestat_set_times
      (i32.const 3) ;; preopened dir
      (i64.const 13136941795642118959) ;; very large timestamp
      (i64.const 0)
      (i32.const 1) ;; atim
    )
    (local.set $err)
    (if
      (i32.ne (i32.const 0) (local.get $err))
      (then (call $proc_exit (local.get $err)))
    )

    (call $proc_exit (i32.load (i32.const 2048)))
  )
  (memory 2)
  (export "memory" (memory 0))
  (export "_start" (func $_start))
)
```

### Screenshots

_No response_

### Any logs you want to share for showing the specific issue

_No response_

### Components

CLI

### WasmEdge Version or Commit you used

d1a4df1827f789cc109fdbc66e2ae8dc35fa7008

### Operating system information

Fedora 39

### Hardware Architecture

amd64

### Compiler flags and options

_No response_

### PR DESCRIPTION
**Pull request by yagehu**
This commit fixes a bug in `toTimespec`.  The duration overflows with a large timestamp because `std::chrono::nanoseconds` is signed 64-bit integer.  Instead, we should explicitly use `uint64_t` because `__wasi_timestamp_t` is unsigned 64-bit.

fixes #3105

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
@hydai  Can you please take a look? Thanks.

**Comment by hydai** [comment]
Hi @yagehu 
I found some WASI tests failed. Could you check if this is related to your commit or not?

**Comment by yagehu** [comment]
@hydai The failing wasi-testsuite case is `pwrite-with-append`, which is a newly added case related to https://github.com/WasmEdge/WasmEdge/issues/3062. So it is not related. Maybe I should remove this test case, it seems most runtimes are failing this and it is not trivial to fix and there's no consensus.

**Review by hydai — APPROVED** [review]

**Pull request merged**
