### PR TITLE
[Docs] Fix outdated contributing page

### PR DESCRIPTION
**Pull request by chenyukang**
Following with outdated contribute page will get this error:

```
-- Linker detection: GNU ld
CMake Error at lib/aot/CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "LLD" with any of
  the following names:

    LLDConfig.cmake
    lld-config.cmake

  Add the installation prefix of "LLD" to CMAKE_PREFIX_PATH or set "LLD_DIR"
  to a directory containing one of the above files.  If "LLD" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/cat/WasmEdge/build/CMakeFiles/CMakeOutput.log".
See also "/home/cat/WasmEdge/build/CMakeFiles/CMakeError.log".
```

llvm-12 is required.

Or a better option is to link the build section to [https://wasmedge.org/book/en/extend/build.html](https://wasmedge.org/book/en/extend/build.html) ?
So we won't need to maintain duplicated parts.

### CODE REVIEW

**Comment by hydai** [comment]
Replacing these sections with the link of `https://wasmedge.org/book/en/extend/build.html` works for me. It will make things simpler for the maintenance.

**Comment by chenyukang** [comment]
I think it's better to remove CONTRIBUTING.md, and add a sub section 8.2 with title: Contribution workflow?

**Comment by hydai** [comment]
> I think it's better to remove CONTRIBUTING.md, and add a sub section 8.2 in the Book with title: Contribution workflow?

Sounds better. We can merge this first. And remove CONTRIBUTING.md in another PR.

**Comment by chenyukang** [comment]
> > I think it's better to remove CONTRIBUTING.md, and add a sub section 8.2 in the Book with title: Contribution workflow?
> 
> Sounds better. We can merge this first. And remove CONTRIBUTING.md in another PR.

Sounds good.

**Review by hydai — APPROVED** [review]

**Pull request merged**
