### PR TITLE
[Docs] Update the Rust dev API part of the book

### PR DESCRIPTION
**Pull request by juntao**
Signed-off-by: Michael Yuan <michael@michaelyuan.com>

### CODE REVIEW

**Comment by hydai** [comment]
@juntao Please resolve the conflicts. Thanks.

**Comment by juntao** [comment]
Resolved

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
@juntao Please resolve the conflicts again. Not sure why I cannot fix it from my side. Thanks.

**Comment by juntao** [comment]
It appears to be ready to merge now. @hydai

**Comment by hydai** [comment]
@juntao No luck. ;-(
截圖 2022-02-22 at 00 01 09@2x

**Comment by juntao** [comment]
I was able to merge. ;)

**Pull request merged**
