### PR TITLE
[Community] nominate new committers

### PR DESCRIPTION
**Pull request by hydai**
In this PR, I am pleased to nominate the following four individuals as new committers:

1. csh(@L-jasmine), the previous reviewer, works hard on reviewing the [WasmEdge Rust SDK](https://github.com/WasmEdge/wasmedge-rust-sdk), WasmEdge Rust Plugin SDK, and other rust-related projects.
2. Vivian Hu(@alabulei1), who applies herself to hosting the community meetings and maintaining the [docs repository](https://github.com/WasmEdge/docs).
3. Wang-Yang Li(@LFsWang), who contributed to the WasmEdge WASI socket in 2022, fixes several Windows bugs and implements the relaxed SIMD proposal(#3311).
4. HanWen Tsao(@grorge123), the mentee of our LFX mentorships program, implements the WASI-NN Neural Speed backend(#3303). After finishing his mentorship, he continued contributing to the Stable Diffusion.cpp plugin(#3444) to extend the ecosystem.

I kindly ask for approval from other maintainers. Please leave your comments and decision below.
/cc @WasmEdge/maintainers

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

**Comment by alabulei1** [comment]
Thanks!

**Review by juntao — APPROVED** [review]

**Review by dannypsnl — APPROVED** [review]

**Review by ibmibmibm — APPROVED** [review]

**Comment by hydai** [comment]
Welcome to the WasmEdge community!

@alabulei1 @L-jasmine, your permissions are being Write(Committer) now.
@LFsWang @grorge123, you are invited to join the repo; please ensure that you approve the invitations. Thanks

**Comment by juntao** [comment]
LGTM!

**Pull request merged**
