### PR TITLE
[Installer] Fix: Append correct path for ggml metal file

### PR DESCRIPTION
**Pull request by SAtacker**
- Fixed https://github.com/WasmEdge/WasmEdge/issues/3078

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by SAtacker** [comment]
There are no tensorflow extensions for x86 macOS.

**Comment by q82419** [comment]
There should be tensorflow extensions for x86 macOS.

```
CONST_urls: {'WasmEdge': 'https://github.com/WasmEdge/WasmEdge/releases/download/0.12.0/WasmEdge-0.12.0-darwin_x86_64.tar.gz', 'WasmEdge_Uninstaller': 'https://raw.githubusercontent.com/WasmEdge/WasmEdge/0.13.5/utils/uninstall.sh', 'image': 'https://github.com/second-state/WasmEdge-image/releases/download/0.12.0/WasmEdge-image-0.12.0-darwin_x86_64.tar.gz', 'tensorflow_deps': 'https://github.com/second-state/WasmEdge-tensorflow-deps/releases/download/TF-2.6.0-CC/WasmEdge-tensorflow-deps-TF-TF-2.6.0-CC-darwin_x86_64.tar.gz', 'tensorflow_lite_deps': 'https://github.com/second-state/WasmEdge-tensorflow-deps/releases/download/TF-2.6.0-CC/WasmEdge-tensorflow-deps-TFLite-TF-2.6.0-CC-darwin_x86_64.tar.gz', 'tensorflow': 'https://github.com/second-state/WasmEdge-tensorflow/releases/download/0.12.0/WasmEdge-tensorflow-0.12.0-darwin_x86_64.tar.gz', 'tensorflow_lite': 'https://github.com/second-state/WasmEdge-tensorflow/releases/download/0.12.0/WasmEdge-tensorflowlite-0.12.0-darwin_x86_64.tar.gz', 'tensorflow_tools': 'https://github.com/second-state/WasmEdge-tensorflow-tools/releases/download/0.12.0/WasmEdge-tensorflow-tools-0.12.0-darwin_x86_64.tar.gz'}
```

You can check the links in the debug info.

**Comment by SAtacker** [comment]
I think these:
```
DEBUG   - Plugin URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_tensorflow-0.13.5-darwin_x86_64.tar.gz
INFO    - Downloading Plugin: wasmedge_tensorflow
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_tensorflow-0.13.5-darwin_x86_64.tar.gz

```
are not found

**Comment by q82419** [comment]
> I think these:
> 
> ```
> DEBUG   - Plugin URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_tensorflow-0.13.5-darwin_x86_64.tar.gz
> INFO    - Downloading Plugin: wasmedge_tensorflow
> ERROR   - Download error from urllib: HTTP Error 404: Not Found
> ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasmedge_tensorflow-0.13.5-darwin_x86_64.tar.gz
> ```
> 
> are not found

Well, the extensions are deprecated and replaced after `0.13.x`. The link you mentioned is the plug-in.
I found that all plug-ins are disappeared on macOS x86_64. @hydai  maybe we should attach them.

**Comment by hydai** [comment]
@SAtacker @q82419 
We should ignore the macOS x86_64 platform temporarily, the reason is that the CI on GitHub had issues when we released the assets.
And currently, I don't think it’s an urgent issue.

**Review by hydai — APPROVED** [review]
Thanks @SAtacker

**Pull request merged**
