### PR TITLE
[Utils] Scripts: Fix #480 and minor issue

### LINKED ISSUE #480: [Install] The script should attempt to install the latest release but not pre-release
Now we have the `0.9.0-rc.1` pre-release, the install script tries to install that. 

1 The script should always install the "latest release". In this case, it should be `0.8.2`.

2 The `0.9.0-rc.1` install also fails with the following message:

```
Fetching WasmEdge-0.9.0~rc.1
Error: Process completed with exit code 8.
```

### PR DESCRIPTION
**Pull request by SAtacker**
Install Script:
* Added Simple filter using inverted grep search

Uninstall Script:
* `ldconfig` replaced with `_ldconfig` which is a wrapper that works for macOS as well

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by SAtacker** [comment]
Test using:
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_install_script/utils/install.sh | bash
```

**Comment by SAtacker** [comment]
Uninstall Testing:
```bash
bash <(wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_install_script/utils/uninstall.sh)
```

**Comment by SAtacker** [comment]
Also there's a difference in packaging for `darwin`
image

**Comment by juntao** [comment]
Can you raise a separate issue about `darwin` package naming? It needs to be consistent. Thanks.

**Pull request merged**
