### PR TITLE
[Socket] unify socket address size

### PR DESCRIPTION
**Pull request by LFsWang**
Signed-off-by: LFsWang <tnst92002@gmail.com>

### Changes

Socket Address should be a 128 bytes buffer.
The first 2 bytes of the address is AddressFamily.
```cpp
#pragma pack(1)
const size_t AddressBufSize = 128;

struct AddressBuf {
   uint16_t AddressFamily;
   uint8_t Address[AddressBufSize  - sizeof(uint16_t)];
};
```

#### Breaking changes (Api)
* ```sockRecvFrom(RiData, RiFlags, AddressBuf, AddressLength, NRead, RoFlags)``` to ```sockGetLoaclAddr(RiData, RiFlags, AddressBuf, AddressLength, PortPtr, NRead, RoFlags)``` 
  *  add PortPtr
* ```sockGetLoaclAddr(Fd, Address, AddrTypePtr, PortPtr)``` to ```sockGetLoaclAddr(Fd, Address, PortPtr)``` 
  * remove AddrTypePtr 
* ```sockGetPeerAddr(Fd, Address, AddrTypePtr, PortPtr)``` to ```sockGetPeerAddr(Fd, Address, PortPtr)``` 
  * remove AddrTypePtr 

#### Changes
```The argument for Address should be 4 or 16 bytes``` to ```The argument for Address should be 128 bytes```
* sockBind
* sockConnect
* sockRecvFrom
* sockSendTo

### CODE REVIEW

**Comment by mfordjody** [comment]
1

**Review by hydai — CHANGES_REQUESTED** [review]

**Review by hydai — APPROVED** [review]

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Hi @LFsWang 
I found the wasi-socket unit tests failed on the macOS. Could you please check them?

**Comment by LFsWang** [comment]
I have tested on MacOS 11.6.8 and passed all testes, therefore I am not sure why failed the socket test on github.

**Comment by hydai** [comment]
Should I merge #1849 before this PR?

**Comment by LFsWang** [comment]
I think #1849 is independent  of this. It is fine.

**Comment by hydai** [comment]
@LFsWang 
Since there are two API breaking changes: `WasiSockGetPeerAddr`, and `WasiSockGetLocalAddr `. It's not possible to merge it before we bump a new version.

Is it possible to separate this PR into two PRs, without the breaking change part and another one? So we can merge those unchanged part.

**Comment by L-jasmine** [comment]
https://github.com/LFsWang/WasmEdge/blob/858992ddd9357123a1055a684e9c71609e945ce2/lib/host/wasi/inode-linux.cpp#L1103-L1115

`sockRecvFrom` is not return `port`.
I think `sockRecvFrom` need add a param `PortPtr` like `sockGetLoaclAddr`

**Comment by LFsWang** [comment]
> https://github.com/LFsWang/WasmEdge/blob/858992ddd9357123a1055a684e9c71609e945ce2/lib/host/wasi/inode-linux.cpp#L1103-L1115
> 
> `sockRecvFrom` is not return `port`. I think `sockRecvFrom` need add a param `PortPtr` like `sockGetLoaclAddr`

I will solve it at #1916 because it will break api.

**Review by hydai — APPROVED** [review]
LGTM

**Pull request merged**
