### PR TITLE
[Docs] Rearrange and rephrase buld instructions

### PR DESCRIPTION
**Pull request by abhinandanudupa**
Just made a few rearrangements and added a link.

### CODE REVIEW

**Comment by abhinandanudupa** [comment]
```powershell
# Download our pre-built LLVM 13 binary
$llvm = "LLVM-13.0.1-win64.zip"
curl -sLO https://github.com/WasmEdge/llvm-windows/releases/download/llvmorg-13.0.1/LLVM-13.0.1-win64.zip -o $llvm
Expand-Archive -Path $llvm
```
https://wasmedge.org/book/en/extend/build_on_windows.html#prepare-the-environment
@hydai We should be removing the part where we are downloading `clang`. Downloading the pre-built `LLVM` is not ideal as users will have to fix an issue related to #1290. Let the users download LLVM and clang with Visual Studio itself. Should I remove this part and add instructions to install from Visual Studio?

**Comment by hydai** [comment]
Sure, the previous steps are using in our CI. 
It's fine to use the VS one.

**Comment by abhinandanudupa** [comment]
Ok, will do it then.

**Comment by abhinandanudupa** [comment]
I raised this PR with the intention of updating it to use `LLVM 14` assuming that the `LLVM` from Visual Studio is being used in the CI and locally. But it turns out that that is not the case as not specifying the directory to the downloaded `LLVM 13` will result in the build system asking for a path to `LLVM` - as tested locally.  Hence it is not useful to continue with the PR - until we use `LLVM 14`.

**Comment by hydai** [comment]
Hi @abhinandanudupa 

It's totally fine to use any version of LLVM including 12, 13, 14, and 15. You can use the latest version from the VS's one.

**Comment by abhinandanudupa** [comment]
Ok, then I will find a way to use the built-in version from Visual Studio.

**Pull request closed without merging**
