### PR TITLE
 [Docs] Discard the WasmEdge Book

### PR DESCRIPTION
**Pull request by alabulei1**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by q82419** [comment]
Please rebase to the latest master and resolve the conflicts.

**Comment by q82419** [comment]
@alabulei1

**Comment by adithyaakrishna** [comment]
@alabulei1 @juntao I have created a Gist here, https://gist.github.com/adithyaakrishna/f19d65263cd4db7701b39676f774ab62 which has all the missing content in the new docs site compared to the books site. 

Instead of adding notes, how about if we set up redirects in `book.toml` to the new docs site?

**Comment by alabulei1** [comment]
Hi @adithyaakrishna ,

I have finished this PR.  Please remove other docs from WasmEdge/WasmEdge repo and migrate content for WasmEdge/docs after this PR is merged. May I know when will you finish? We can process this through small PRs. 

Redirecting is a good idea. But we both aren't familiar with book.toml. So I still think the first priority is to remove the old docs from WasmEdge/WasmEdge. Let's do this firstly.

**Comment by hydai** [comment]
Hi @adithyaakrishna 
Auto redirect is an awesome idea. I would like to have it in another PR. To make this happen, I think I will need a table for the relationship between the new site and old site.

**Comment by alabulei1** [comment]
> @alabulei1 Can you push once you finish all your commits?

Sorry for missing this. I worked on this PR via the GitHub UI. I will take care of it next time.

**Pull request merged**
