### PR TITLE
[Component] resourcetype loader

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by dannypsnl** [comment]
@hydai please mark this as draft.

**Comment by dannypsnl** [comment]
I found why the loader is failed, the current ([63ffc9](https://github.com/WebAssembly/component-model/commit/abeee91b8753b811fce7528b85d76b85733c2839)) syntax is

```
importname' ::= 0x00 len:<u32> in:<importname>                       => in  (if len = |in|)
exportname' ::= 0x00 len:<u32> en:<exportname>                       => en  (if len = |en|)
```

the old version ([9fde36](https://github.com/WebAssembly/component-model/commit/9fde36937e0017a14b5f79d3898d33090f4b2aca)) is

```
import      ::= in:<importname> ed:<externdesc>                      => (import in ed)
export      ::= en:<exportname> si:<sortidx> ed?:<externdesc>?       => (export en si ed?)
exportname  ::= 0x00 n:<name>                                        => n
              | 0x01 i:<iid'>                                        => (interface i)
iid'        ::= len:<u32> i:<iid>                                    => "i" (if len = |i|)
importname  ::= en:<exportname>                                      => en
              | 0x02 n:<name> s:<string> i?:<integrity'>?            => n (url s i?)
              | 0x03 n:<name> s:<string> i?:<integrity'>?            => n (relative-url s i?)
              | 0x04 n:<name> i:<integrity'>                         => n i
              | 0x05 p:<pkgid'> i?:<integrity'>?                     => (locked-dep p i?)
              | 0x06 p:<pkgidset'>                                   => (unlocked-dep p)
pkgid'      ::= len:<u32> p:<pkgid>                                  => "p" (if len = |p|)
pkgidset'   ::= len:<u32> p:<pkgidset>                               => "p" (if len = |p|)
integrity'  ::= len:<u32> im:<integrity-metadata>                    => (integrity "im") (if len = |im|)
```

## Tools

The packages below are what I'm using to generate component binary.

```
[package]]
name = "cargo-component-bindings"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "545e48ba821e07f93c97aea897bee6d407de4d58947f914160131f3d78b2c704"
dependencies = [
 "cargo-component-macro",
 "wit-bindgen",
]

[[package]]
name = "cargo-component-macro"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e198ee0b668e902b43b5e7d2e9620a3891d2632429b3ba66e1ceea455053cbf5"
dependencies = [
 "proc-macro2",
 "quote",
 "syn",
]
```

**Comment by dannypsnl** [comment]
After I update to `cargo-component-component 0.15.0`, I got loader in this PR right, all leave is wasi packages problem.

**Pull request merged**
