### PR TITLE
[CI] Build extensions on manylinux_2_28 x86_64

### LINKED ISSUE #3512: build fail: wasm_bpf on manylinux_2_28 (gcc 13)
### Summary

```
CMake Deprecation Warning at build/_deps/gtest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at build/_deps/gtest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Downloading SIMDJSON source
-- Adding -Og to compile flag
-- Downloading SIMDJSON source -- done
-- Downloading the WASM spec test suite
-- Downloading the WASM spec test suite -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/core
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/core -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/multi-memory
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/multi-memory -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/tail-call
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/tail-call -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/extended-const
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/extended-const -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/threads
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/threads -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/function-references
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/function-references -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/gc
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/gc -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/exception-handling
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/exception-handling -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/exception-handling-legacy
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/exception-handling-legacy -- done
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/relaxed-simd
-- Copying test suite to /__w/WasmEdge/WasmEdge/build/test/spec/testSuites/relaxed-simd -- done
Downloading wasm-bpf
Downloaded wasm-bpf
-- Version: 10.2.1
-- Build type: Release
-- Build spdlog: 1.13.0
-- Build type: Release
-- Trying to get libbpf..
-- Build libbpf with pkg-config: OFF
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2")
-- Try to get libbpf through PkgConfig
-- Checking for module 'libbpf>=1.2.0'
--   Package 'libbpf', required by 'virtual:world', not found
-- LIBBPF_FOUND=
-- libbpf not found using pkgconfig
-- Try to get libbpf through the pre-defined LIBBPF_SOURCE_DIR
-- LIBBPF_SOURCE_DIR not defined
-- Try to get libbpf through FetchContent
-- Fetching libbpf..
-- Fetched libbpf
-- SOURCE_ROOT=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src
-- LIBBPF_INCLUDE_DIRS=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/root/usr/include;/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/include/uapi;/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/include
-- LIBBPF_LIBRARIES=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/libbpf.so
-- LIBBPF_TARGET_NAME=libbpf
-- LIBBPF_LIBRARIES_STATIC=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/libbpf.a
-- LIBBPF_SOURCE=fetch-content
-- LIBBPF_DEP_LIBRARIES=elf;z
-- LIBBPF_DEP_LIBRARIES_STATIC=
-- Link libbpf statically
-- Configuring done (7.5s)
-- Generating done (0.1s)
-- Build files have been written to: /__w/WasmEdge/WasmEdge/build
[1/[29](https://github.com/WasmEdge/WasmEdge/actions/runs/9710756208/job/26802302179?pr=3421#step:8:30)] Creating directories for 'libbpf'
[2/29] No download step for 'libbpf'
[3/29] No update step for 'libbpf'
[4/29] No patch step for 'libbpf'
[5/29] Performing configure step for 'libbpf'
[6/29] Generating /__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/simple_map.bpf.o, /__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/simple_ringbuf.bpf.o
make: Entering directory '/__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/bpf-sources'
rm -rf simple_map.bpf.o
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -c simple_map.bpf.c -o simple_map.bpf.o
llvm-strip -g simple_map.bpf.o
cp simple_map.bpf.o ../simple_map.bpf.o
rm -rf simple_ringbuf.bpf.o
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -c simple_ringbuf.bpf.c -o simple_ringbuf.bpf.o
llvm-strip -g simple_ringbuf.bpf.o
cp simple_ringbuf.bpf.o ../simple_ringbuf.bpf.o
make: Leaving directory '/__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/bpf-sources'
[7/29] Performing build step for 'libbpf'
FAILED: plugins/wasm_bpf/libbpf/src/libbpf-stamp/libbpf-build _deps/libbpf-src/src/build/libbpf.so _deps/libbpf-src/src/build/libbpf.a /__w/WasmEdge/WasmEdge/build/plugins/wasm_bpf/libbpf/src/libbpf-stamp/libbpf-build /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/libbpf.so /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/libbpf.a 
cd /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src && NO_PKG_CONFIG=1 OBJDIR=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build DESTDIR=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/root CFLAGS=-fPIC make -C /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src install && /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/bin/cmake -E touch /__w/WasmEdge/WasmEdge/build/plugins/wasm_bpf/libbpf/src/libbpf-stamp/libbpf-build
make: Entering directory '/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src'
  MKDIR    /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs
  CC       /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs/bpf.o
  CC       /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs/btf.o
btf.c:18:10: fatal error: gelf.h: No such file or directory
   18 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:1[31](https://github.com/WasmEdge/WasmEdge/actions/runs/9710756208/job/26802302179?pr=3421#step:8:32): /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs/btf.o] Error 1
make: Leaving directory '/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src'
[8/29] Generating /__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/bootstrap.bpf.o
make: Entering directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/bootstrap'
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I../../runtime/cpp/third_party/vmlinux/x86/ -I../../runtime/cpp/third_party/ -idirafter /opt/rh/gcc-toolset-13/root/usr/lib64/clang/17/include -idirafter /usr/local/include -idirafter /usr/include -c bootstrap.bpf.c -o bootstrap.bpf.o
llvm-strip -g bootstrap.bpf.o # strip useless DWARF info
make: Leaving directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/bootstrap'
[9/29] Generating /__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/runqlat.bpf.o
make: Entering directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/runqlat'
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I../../runtime/cpp/third_party/vmlinux/x86/ -I../../runtime/cpp/third_party/ -idirafter /opt/rh/gcc-toolset-13/root/usr/lib64/clang/17/include -idirafter /usr/local/include -idirafter /usr/include -c runqlat.bpf.c -o runqlat.bpf.o
runqlat.bpf.c:119:5: warning: __sync builtin operation MUST have natural alignment (consider using __atomic). [-Wsync-alignment]
  119 |     __sync_fetch_and_add(&histp->slots[slot], 1);
      |     ^
1 warning generated.
llvm-strip -g runqlat.bpf.o # strip useless DWARF info
make: Leaving directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/runqlat'
[10/29] Building CXX object _deps/gtest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[11/29] Building CXX object _deps/gtest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
ninja: build stopped: subcommand failed.
```

### Appendix

[CI link](https://github.com/WasmEdge/WasmEdge/actions/runs/9710756208/job/26802302179)

### PR DESCRIPTION
**Pull request by 0yi0**
Fix #3512 and enable workflows.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

**Comment by 0yi0** [comment]
## WASI-NN PyTorch
Link to log: https://github.com/WasmEdge/WasmEdge/actions/runs/9414979215/job/25935178141
```
[16/16] Linking CXX executable test/plugins/wasi_nn/wasiNNTests
FAILED: test/plugins/wasi_nn/wasiNNTests 
: && /opt/rh/gcc-toolset-13/root/usr/bin/c++ -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -Wl,--export-dynamic -rdynamic test/plugins/wasi_nn/CMakeFiles/wasiNNTests.dir/wasi_nn.cpp.o -o test/plugins/wasi_nn/wasiNNTests  -Wl,-rpath,"/root/libtorch/lib:\$ORIGIN/../../../lib/api"  /root/libtorch/lib/libtorch.so  /root/libtorch/lib/libc10.so  lib/libgtest.a  lib/libgtest_main.a  lib/api/libwasmedge.so.0.1.0  -Wl,--no-as-needed,"/root/libtorch/lib/libtorch_cpu.so" -Wl,--as-needed  /root/libtorch/lib/libc10.so  -Wl,--no-as-needed,"/root/libtorch/lib/libtorch.so" -Wl,--as-needed  lib/libgtest.a  _deps/spdlog-build/libspdlog.a  -pthread  _deps/fmt-build/libfmt.a && :
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger.h:50:18: warning: type ‘struct logger’ violates the C++ One Definition Rule [-Wodr]
   50 | class SPDLOG_API logger {
      |                  ^
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger.h:50:18: note: a different type is defined in another translation unit
   50 | class SPDLOG_API logger {
      |                  ^
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger.h:308:17: note: the first difference of corresponding definitions is field ‘name_’
  308 |     std::string name_;
      |                 ^
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger.h:308:17: note: a field of same name but different type is defined in another translation unit
  308 |     std::string name_;
      |                 ^
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger.h:50:18: note: type name ‘std::string’ should match type name ‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >’
   50 | class SPDLOG_API logger {
      |                  ^
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger.h:362:10: warning: type of ‘log_it_’ does not match original declaration [-Wlto-type-mismatch]
  362 |     void log_it_(const details::log_msg &log_msg, bool log_enabled, bool traceback_enabled);
      |          ^
/__w/WasmEdge/WasmEdge/build/_deps/spdlog-src/include/spdlog/logger-inl.h:124:20: note: ‘log_it_’ was previously declared here
  124 | SPDLOG_INLINE void logger::log_it_(const spdlog::details::log_msg &log_msg,
      |                    ^
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o: in function `testing::AssertionResult::AppendMessage(testing::Message const&)':
<artificial>:(.text+0x[231](https://github.com/WasmEdge/WasmEdge/actions/runs/9414979215/job/25935178141#step:8:232)d): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o: in function `testing::AssertionResult& testing::AssertionResult::operator<< <char [12]>(char const (&) [12])':
<artificial>:(.text+0x2959): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o: in function `testing::AssertionResult& testing::AssertionResult::operator<< <char const*>(char const* const&)':
<artificial>:(.text+0x2a9a): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o: in function `testing::AssertionResult& testing::AssertionResult::operator<< <char [3]>(char const (&) [3])':
<artificial>:(.text+0x2bc9): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o: in function `testing::AssertionResult& testing::AssertionResult::operator<< <char [5]>(char const (&) [5])':
<artificial>:(.text+0x2cf9): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o: in function `WasiNNTest_PyTorchBackend_Test::TestBody()':
<artificial>:(.text+0x40de): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x4494): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x460b): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x4783): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x48fb): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x60e9): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x645a): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x665e): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x683c): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x7886): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x7953): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x7a20): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans0.ltrans.o:<artificial>:(.text+0x7aeb): more undefined references to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)' follow
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans4.ltrans.o: in function `testing::AssertionResult testing::internal::CmpHelperNE<WasmEdge::Runtime::Instance::FunctionInstance*, decltype(nullptr)>(char const*, char const*, WasmEdge::Runtime::Instance::FunctionInstance* const&, decltype(nullptr) const&) [clone .constprop.0]':
<artificial>:(.text+0x4fec): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: <artificial>:(.text+0x5084): undefined reference to `testing::Message::GetString() const'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans4.ltrans.o: in function `(anonymous namespace)::createModule(std::basic_string_view<char, std::char_traits<char> >) [clone .constprop.0]':
<artificial>:(.text+0x52b3): undefined reference to `WasmEdge::Plugin::Plugin::load(std::filesystem::path const&)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans5.ltrans.o: in function `testing::AssertionResult testing::internal::CmpHelperEQ<int, unsigned int>(char const*, char const*, int const&, unsigned int const&) [clone .constprop.0]':
<artificial>:(.text+0x2b1): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans5.ltrans.o: in function `testing::AssertionResult testing::internal::CmpHelperEQ<int, unsigned int>(char const*, char const*, int const&, unsigned int const&) [clone .constprop.1]':
<artificial>:(.text+0x391): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cczXqhvU.ltrans5.ltrans.o: in function `testing::AssertionResult testing::internal::CmpHelperEQ<unsigned int, int>(char const*, char const*, unsigned int const&, int const&) [clone .constprop.0]':
<artificial>:(.text+0x472): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
collect2: error: ld returned 1 exit status
```

**Comment by 0yi0** [comment]
### wasm bpf
Link to log: https://github.com/WasmEdge/WasmEdge/actions/runs/9414979215/job/25935178340
```
[7/29] Performing build step for 'libbpf'
FAILED: plugins/wasm_bpf/libbpf/src/libbpf-stamp/libbpf-build _deps/libbpf-src/src/build/libbpf.so _deps/libbpf-src/src/build/libbpf.a /__w/WasmEdge/WasmEdge/build/plugins/wasm_bpf/libbpf/src/libbpf-stamp/libbpf-build /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/libbpf.so /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/libbpf.a 
cd /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src && NO_PKG_CONFIG=1 OBJDIR=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build DESTDIR=/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/root CFLAGS=-fPIC make -C /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src install && /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/bin/cmake -E touch /__w/WasmEdge/WasmEdge/build/plugins/wasm_bpf/libbpf/src/libbpf-stamp/libbpf-build
make: Entering directory '/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src'
  MKDIR    /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs
  CC       /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs/bpf.o
  CC       /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs/btf.o
btf.c:18:10: fatal error: gelf.h: No such file or directory
   18 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:131: /__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src/build/staticobjs/btf.o] Error 1
make: Leaving directory '/__w/WasmEdge/WasmEdge/build/_deps/libbpf-src/src'
[8/29] Generating /__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/bootstrap.bpf.o
make: Entering directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/bootstrap'
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I../../runtime/cpp/third_party/vmlinux/x86/ -I../../runtime/cpp/third_party/ -idirafter /opt/rh/gcc-toolset-13/root/usr/lib64/clang/17/include -idirafter /usr/local/include -idirafter /usr/include -c bootstrap.bpf.c -o bootstrap.bpf.o
llvm-strip -g bootstrap.bpf.o # strip useless DWARF info
make: Leaving directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/bootstrap'
[9/29] Generating /__w/WasmEdge/WasmEdge/test/plugins/wasm_bpf/assets/runqlat.bpf.o
make: Entering directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/runqlat'
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I../../runtime/cpp/third_party/vmlinux/x86/ -I../../runtime/cpp/third_party/ -idirafter /opt/rh/gcc-toolset-13/root/usr/lib64/clang/17/include -idirafter /usr/local/include -idirafter /usr/include -c runqlat.bpf.c -o runqlat.bpf.o
runqlat.bpf.c:[119](https://github.com/WasmEdge/WasmEdge/actions/runs/9414979215/job/25935178340#step:8:120):5: warning: __sync builtin operation MUST have natural alignment (consider using __atomic). [-Wsync-alignment]
  119 |     __sync_fetch_and_add(&histp->slots[slot], 1);
      |     ^
1 warning generated.
llvm-strip -g runqlat.bpf.o # strip useless DWARF info
make: Leaving directory '/__w/WasmEdge/WasmEdge/build/_deps/wasm_bpf-src/examples/runqlat'
[10/29] Building CXX object _deps/gtest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[11/29] Building CXX object _deps/gtest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
ninja: build stopped: subcommand failed.
```

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
`checkout@v3` is not compatible with manylinux2014 because of the node20 issue.

**Comment by 0yi0** [comment]
> `checkout@v3` is not compatible with manylinux2014 because of the node20 issue.

It's `checkout@v4` not compatible. `manylinux2014` is already failing before this PR and should be irrelevant to `actions/checkout`.

**Pull request merged**
