### PR TITLE
[Plugin] Fix typo: s/Registory/Registry/g

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by dannypsnl — APPROVED** [review]
@hydai This seems correct, do you remember any reason for spelling?

**Comment by hydai** [comment]
> @hydai This seems correct, do you remember any reason for spelling?

I believe it is just a mistake ;-)

**Comment by hydai** [comment]
Hi @AkihiroSuda 
Could you please try to update this branch again?
I am trying to understand why the merge button is getting gray and not allowing me to merge it.

CleanShot 2023-12-26 at 09 46 40

**Review by hydai — APPROVED** [review]
Nice catch. Thanks.

**Review by q82419 — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Rebased

**Pull request merged**
