### PR TITLE
Upgrade openvino 2.0

### LINKED ISSUE #3140: feat: Upgrade to OpenVINO API 2.0
### Summary

PR #3128 plans to introduce the grpc service into the WasmEdge repository. However, due to the conflict between the grpc package and OpenVINO, we must upgrade OpenVINO to a newer version. After using a new version of OpenVINO, another issue occurred: it required us to upgrade the Inference Engine API. 

### Details

The older API is planned to be deprecated in the `2024.0` version. Please follow the official OpenVINO guide to do the upgrade.
Ref: https://docs.openvino.ai/2022.3/openvino_2_0_transition_guide.html

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by CaptainVincent**
Some points of my confusion during the work integration to 2.0 API. 

I noticed that the shape of the input tensor passed from WebAssembly (wasm) is NHWC, but the tensor dimensions in the parameters are given as [1, 3, 224, 224], leading to parsing errors. 
Currently, I manually hardcode {1, 224, 224, 3} in `openvino.cpp` to bypass this issue. 

@apepkuss , could you please take a look at the original example and check if the processing of image to tensor is handled correctly? Or if there's any misunderstanding on my part, please help correct me. Thanks!

Fix #3140

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by apepkuss** [comment]
@CaptainVincent If you use `mobilenet-v2-1.0-224` model in your test, I recommend using [this link](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/mobilenet-v2-1.0-224/model.yml) as a reference of layout. It can guarantee that the input image tensor and the model have the same layout. The model is of `NHWC`, so it's recommended to test your code with another model of `NCHW` layout. `NCHW` was the default layout of OpenVINO. For the conversion of images to tensors, you can try https://crates.io/crates/image2tensor. Intel guys upgraded it a lot.

**Comment by hydai** [comment]
@CaptainVincent 
Could you please rebase the branch?

**Review by hydai — APPROVED** [review]

**Comment by CaptainVincent** [comment]
I am using the test model that was mobilenet_v2_1.0_224 and downloaded by [script](https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/openvino-mobilenet-image/download_mobilenet.sh).
According to the OpenVINO [documentation](https://docs.openvino.ai/2023.3/omz_models_model_mobilenet_v2_1_0_224.html) and the information in the [metadata](https://github.com/intel/openvino-rs/blob/59e1fa9d415919023afba402d3445f08ae0db390/crates/openvino/tests/fixtures/mobilenet/mobilenet.xml#L5258), my understanding is that the input tensor is also use `NHWC` layout (same with you). However, what confuses me is that the original dim information from the [wasm](https://github.com/second-state/WasmEdge-WASINN-examples/blob/5db620f38de5dfd86769ca3998588bec3bce8f3a/openvino-mobilenet-image/rust/src/main.rs#L25) appears to be in `NCHW` order even real data is `NHWC`. I assumed that this dimension info is used to inform the inference engine about the layout of the input data (image). Due to unexpected information passed from wasm, so I have to [hardcode](https://github.com/WasmEdge/WasmEdge/blob/ca89655ee5b7814a2f60627da2d45c87b33971b9/plugins/wasi_nn/openvino.cpp#L100) the logic at the plugin level. At the same time, I also don't understand why the 0.2 API is workable before. Any idea?

**Pull request merged**
