### PR TITLE
[SIMD] add Relaxed simd

### LINKED ISSUE #3282: feat: support relaxed simd proposal
### Summary

The relaxed SIMD proposal is now in Phase 4. We should consider to implement it.

Ref: https://github.com/WebAssembly/relaxed-simd

### Details

Implement the whole spec of the relaxed SIMD proposal, including the interpreter, AOT, and JIT.

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by LFsWang**
Fixes #3282

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by LFsWang** [comment]
@q82419 Hello, may you help me review the code?

And here is the relaxed simd testsuits form Webassembly. I have tested and passed and It's can put into the core testsuits.

But one case `relaxed_simd_relaxed_dot_product` can not be complied by wabt because missing the opcode `i16x8.relaxed_dot_i8x16_i7x16_s`, however I kept that wast in the folder.

[relaxed_simd_tests.zip](https://github.com/WasmEdge/WasmEdge/files/15282325/relaxed_simd_tests.zip)

**Comment by q82419** [comment]
> @q82419 Hello, may you help me review the code?
> 
> And here is the relaxed simd testsuits form Webassembly. I have tested and passed and It's can put into the core testsuits.
> 
> But one case `relaxed_simd_relaxed_dot_product` can not be complied by wabt because missing the opcode `i16x8.relaxed_dot_i8x16_i7x16_s`, however I kept that wast in the folder.
> 
> [relaxed_simd_tests.zip](https://github.com/WasmEdge/WasmEdge/files/15282325/relaxed_simd_tests.zip)

I'll review in these days. Thanks!

**Review by q82419 — CHANGES_REQUESTED** [review]
Please modify for the following changes:

1. Rebase on to the master. The `RelaxSIMD` proposal is added into the enum.
2. Filter the instructions in the `Configure` class. This will print log to ask developers to turn on this proposal.
3. Add the `relaxed-simd` spec test. I've updated the spec test in the `wasm-dev` branch, includes the test cannot be generated by `wabt` you mentioned. Please change to that branch.

Thanks!

**Review by q82419 — CHANGES_REQUESTED** [review]
You should add the spec test data of relaxed SIMD of CMake for copy step here:
https://github.com/WasmEdge/WasmEdge/blob/master/test/spec/CMakeLists.txt#L27
And also add the spec test here:
https://github.com/WasmEdge/WasmEdge/blob/master/test/spec/spectest.cpp#L254
Remind the proposal enum mapping here:
https://github.com/WasmEdge/WasmEdge/blob/master/test/api/helper.cpp#L25
Thanks.

**Comment by hydai** [comment]
Please run clang-format first.

**Comment by LFsWang** [comment]
I found `X86SSSE3PMAddUbSw128` is not work on edge case in relaxed product, but the alternative way is work, I will read the spec to check it.

**Comment by LFsWang** [comment]
> I found `X86SSSE3PMAddUbSw128` is not work on edge case in relaxed product, but the alternative way is work, I will read the spec to check it.

[ssse3test.cpp.txt](https://github.com/user-attachments/files/15759376/ssse3test.cpp.txt)

I found that is a bug in testcase, I will send a pr to update the testcase. The code with `X86SSSE3PMAddUbSw128` is fine.

**Comment by q82419** [comment]
Please wait for us for fixing the Windows build. Thanks!

**Comment by hydai** [comment]
@q82419 
Please check if the other parts are reviewed. So we can merge it immediately when the Windows issue is resolved.

**Comment by hydai** [comment]
@LFsWang 
The windows related CI issues are fixed. Please rebase to the latest master.

@q82419 Please review the code.

**Comment by q82419** [comment]
Seems like the test on Windows-MSVC failed for interpreter.
The other OSes are OK.

**Comment by LFsWang** [comment]
> Seems like the test on Windows-MSVC failed for interpreter. The other OSes are OK.

fixed

**Review by q82419 — APPROVED** [review]
LGTM!

**Review by dannypsnl — APPROVED** [review]

**Pull request merged**
