### PR TITLE
[Community] nominate a new reviewer

### PR DESCRIPTION
**Pull request by hydai**
In this PR, I am pleased to nominate Shao-Yu Yu(@PeterD1524) as a new reviewer.

He was a mentee in our LFX Mentorship Program, where he focused on implementing the WASI-NN Piper backend (#3499) during the mentorship period.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

**Comment by hydai** [comment]
3/4 maintainers approved. I am merging this.

cc @ibmibmibm @q82419 @juntao 
I need approval on GitHub to merge this because I am the author of this PR. I am not able to merge it by myself.

**Review by q82419 — APPROVED** [review]

**Pull request merged**
