### PR TITLE
[WASI-NN] ggml backend: enable cuBLAS and bump from b1309 to b1383.

### LINKED ISSUE #2951: agx orin, free(): invalid pointer Aborted (core dumped)
### Summary

I followd this tutorial below and use AGX Orin device:

https://blog.stackademic.com/fast-and-portable-llama2-inference-on-the-heterogeneous-edge-a62508e82359

When I run 
`wasmedge --dir .:. --nn-preload default:GGML:CPU:llama-2-7b-chat.Q5_K_M.gguf wasmedge-ggml-llama-interactive.wasm default
`

it throws "free(): invalid pointer Aborted (core dumped)"

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by hydai**
Fixes #2951

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
@dm4 
This is almost done. However, I have to set up the ubuntu20.04 aarch64 workflow in the same PR to fix the #2951.
Could you please review the remaining part first? After I finish the workflow part, I will push it in this PR.

**Comment by VestigeJ** [comment]
looks like CI needs to be re-run this may have been transient from codecov failing to upload results

**Comment by hydai** [comment]
@dm4 
This PR is ready, please review.

**Review by dm4 — DISMISSED** [review]
LGTM

**Pull request merged**
