### PR TITLE
[Docs] Added an Artifact Hub badge

### LINKED ISSUE #2972: Get an Artifact Hub badge
Check out docs: https://clomonitor.io/docs/topics/checks/#artifact-hub-badge

### PR DESCRIPTION
**Pull request by dhruvmehtaaa**
Fixes #2972 

@alabulei1 Can you please review this?

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
Hi @dhruvmehtaaa 

I think the first step is to publish WasmEdge on Artifact Hub, not just add a link.

**Comment by dhruvmehtaaa** [comment]
I am reading more on this. I will give you an update as soon as possible.

**Comment by dhruvmehtaaa** [comment]
@alabulei1 The badge now links to a helm chart to configure a kubernetes cluster to run WASM services.

**Pull request closed without merging**
