### PR TITLE
[UTILS] Streamline the install scripts #369

### PR DESCRIPTION
**Pull request by SAtacker**
* To have a Unified set of install scripts for wasmedge itself
along with its extensions.
* Dependencies are incorporated within this script for wasmedge.
* It should work perfectly fine on Debian-based distros.

### CODE REVIEW

**Comment by SAtacker** [comment]
These scripts can be merged into one single script. I'll wait for the review as these may reduce/grow depending on the review.
Thanks.

**Comment by juntao** [comment]
Can we combine the multiple install scripts into one? By default, it just installs `wasmedge` and its libraries / headers. But we can give it a flag on the command line to install dependencies and `wasmegde-tensorflow-lite` etc.

**Comment by juntao** [comment]
This new version looks great! Can we have a `uninstall_wasmedge.sh` script as well. It takes the same set of arguments as the install script. It does not remove any system libraries -- just the ones we installed and can be recovered via another run of the install script.

**Comment by juntao** [comment]
Can you default to version 0.8.2? Thanks.

**Comment by juntao** [comment]
When I tried this on a fresh Ubuntu 20.04, the script stopped and asked me to manually input the following. Can we change this to "headless" install? That is, why does the user need to give the timezone info during install?

```
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
Geographic area: 12

Please select the city or region corresponding to your time zone.

  1. Alaska    4. Central  7. Indiana-Starke  10. Pacific
  2. Aleutian  5. Eastern  8. Michigan        11. Samoa
  3. Arizona   6. Hawaii   9. Mountain
Time zone: 4
Progress: [ 65%] [#####################################.....................]
```

**Comment by SAtacker** [comment]
> Can you default to version 0.8.2? Thanks.

Instead, can we use
```bash
VERSION=$(git -c 'versionsort.suffix=-' \
    ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/WasmEdge/WasmEdge.git '*.*.*' \
    | tail --lines=1 \
    | cut --delimiter='/' --fields=3)
```
This will make it default to the latest release as per semantic versioning.

**Comment by SAtacker** [comment]
> When I tried this on a fresh Ubuntu 20.04, the script stopped and asked me to manually input the following. Can we change this to "headless" install? That is, why does the user need to give the timezone info during install?
> 
> ```
> Configuring tzdata
> ------------------
> 
> Please select the geographic area in which you live. Subsequent configuration
> questions will narrow this down by presenting a list of cities, representing
> the time zones in which they are located.
> 
>   1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
>   2. America     5. Arctic     8. Europe    11. SystemV
>   3. Antarctica  6. Asia       9. Indian    12. US
> Geographic area: 12
> 
> Please select the city or region corresponding to your time zone.
> 
>   1. Alaska    4. Central  7. Indiana-Starke  10. Pacific
>   2. Aleutian  5. Eastern  8. Michigan        11. Samoa
>   3. Arizona   6. Hawaii   9. Mountain
> Time zone: 4
> Progress: [ 65%] [#####################################.....................]
> ```

I believe this is happening due to the environment variable settings for that image Ref- [here](https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image)

**Comment by SAtacker** [comment]
Summary:
* Un-Interactive if path is provided via command line args
* Provided `trap` for better handling
* Outputs version mismatch which will help in keeping consistency with namings

Takes around 6 minutes for complete installation on a fresh, latest ubuntu image
Complete Output: [here](https://pastebin.com/VKsBi4QF)

**Comment by juntao** [comment]
Since this script requires sudo or root user privileges, I suggest that we explicitly check that at the beginning, and throw an error if the user does not have sufficient privileges.

If the user does not give a path, I suggest that the script defaults to install in $HOME/.wasmedge -- you may need to create this directory first and set $HOME/.wasmedge/bin into the PATH at the end. You can refer to the Rust installation script to see how it is done. Thanks!

**Comment by juntao** [comment]
I am seeing this error when running `-e all`

```
+ '[' '!' 'wasmedge-tensorflow version 0.8.2-rc.2' = '' ']'
+ echo 'Version strings mismatch for wasmedge-tensorflow'
Version strings mismatch for wasmedge-tensorflow
+ echo 'Found wasmedge-tensorflow version 0.8.2-rc.2'
Found wasmedge-tensorflow version 0.8.2-rc.2
+ echo 'Initially chosen 0.8.2-rc2'
Initially chosen 0.8.2-rc2
+ for var in "$@"
++ wasmedgec-tensorflow --version
+ V='wasmedgec-tensorflow version 0.8.2-rc.2'
+ '[' 'wasmedgec-tensorflow version 0.8.2-rc.2' = 'wasmedgec-tensorflow version 0.8.2-rc2' ']'
++ echo 'wasmedgec-tensorflow version 0.8.2-rc.2'
++ grep 'wasmedgec-tensorflow version'
+ output='wasmedgec-tensorflow version 0.8.2-rc.2'
+ '[' '!' 'wasmedgec-tensorflow version 0.8.2-rc.2' = '' ']'
+ echo 'Version strings mismatch for wasmedgec-tensorflow'
Version strings mismatch for wasmedgec-tensorflow
+ echo 'Found wasmedgec-tensorflow version 0.8.2-rc.2'
Found wasmedgec-tensorflow version 0.8.2-rc.2
+ echo 'Initially chosen 0.8.2-rc2'
Initially chosen 0.8.2-rc2
+ for var in "$@"
++ wasmedge-tensorflow-lite --version
+ V='wasmedge-tensorflow-lite version 0.8.2-rc.2'
+ '[' 'wasmedge-tensorflow-lite version 0.8.2-rc.2' = 'wasmedge-tensorflow-lite version 0.8.2-rc2' ']'
++ echo 'wasmedge-tensorflow-lite version 0.8.2-rc.2'
++ grep 'wasmedge-tensorflow-lite version'
+ output='wasmedge-tensorflow-lite version 0.8.2-rc.2'
+ '[' '!' 'wasmedge-tensorflow-lite version 0.8.2-rc.2' = '' ']'
+ echo 'Version strings mismatch for wasmedge-tensorflow-lite'
Version strings mismatch for wasmedge-tensorflow-lite
+ echo 'Found wasmedge-tensorflow-lite version 0.8.2-rc.2'
Found wasmedge-tensorflow-lite version 0.8.2-rc.2
+ echo 'Initially chosen 0.8.2-rc2'
Initially chosen 0.8.2-rc2
+ trap - EXIT
```

**Comment by SAtacker** [comment]
> I am seeing this error when running `-e all`
> 
> ```
> + '[' '!' 'wasmedge-tensorflow version 0.8.2-rc.2' = '' ']'
> + echo 'Version strings mismatch for wasmedge-tensorflow'
> Version strings mismatch for wasmedge-tensorflow
> + echo 'Found wasmedge-tensorflow version 0.8.2-rc.2'
> Found wasmedge-tensorflow version 0.8.2-rc.2
> + echo 'Initially chosen 0.8.2-rc2'
> Initially chosen 0.8.2-rc2
> + for var in "$@"
> ++ wasmedgec-tensorflow --version
> + V='wasmedgec-tensorflow version 0.8.2-rc.2'
> + '[' 'wasmedgec-tensorflow version 0.8.2-rc.2' = 'wasmedgec-tensorflow version 0.8.2-rc2' ']'
> ++ echo 'wasmedgec-tensorflow version 0.8.2-rc.2'
> ++ grep 'wasmedgec-tensorflow version'
> + output='wasmedgec-tensorflow version 0.8.2-rc.2'
> + '[' '!' 'wasmedgec-tensorflow version 0.8.2-rc.2' = '' ']'
> + echo 'Version strings mismatch for wasmedgec-tensorflow'
> Version strings mismatch for wasmedgec-tensorflow
> + echo 'Found wasmedgec-tensorflow version 0.8.2-rc.2'
> Found wasmedgec-tensorflow version 0.8.2-rc.2
> + echo 'Initially chosen 0.8.2-rc2'
> Initially chosen 0.8.2-rc2
> + for var in "$@"
> ++ wasmedge-tensorflow-lite --version
> + V='wasmedge-tensorflow-lite version 0.8.2-rc.2'
> + '[' 'wasmedge-tensorflow-lite version 0.8.2-rc.2' = 'wasmedge-tensorflow-lite version 0.8.2-rc2' ']'
> ++ echo 'wasmedge-tensorflow-lite version 0.8.2-rc.2'
> ++ grep 'wasmedge-tensorflow-lite version'
> + output='wasmedge-tensorflow-lite version 0.8.2-rc.2'
> + '[' '!' 'wasmedge-tensorflow-lite version 0.8.2-rc.2' = '' ']'
> + echo 'Version strings mismatch for wasmedge-tensorflow-lite'
> Version strings mismatch for wasmedge-tensorflow-lite
> + echo 'Found wasmedge-tensorflow-lite version 0.8.2-rc.2'
> Found wasmedge-tensorflow-lite version 0.8.2-rc.2
> + echo 'Initially chosen 0.8.2-rc2'
> Initially chosen 0.8.2-rc2
> + trap - EXIT
> ```

The 
```
'Found wasmedge-tensorflow-lite version 0.8.2-rc.2'
Found wasmedge-tensorflow-lite version 0.8.2-rc.2
+ echo 'Initially chosen 0.8.2-rc2
```
indicates that there is inconsistency in the naming of releases. I can simply change the script to match without delimiters but it was intentional to get notice of `0.8.2-rc.2` vs `0.8.2-rc2`

**Comment by SAtacker** [comment]
> Hmm, I thought the script will find the latest versions of everything by default. It should work even if the version tag has a typo (in this case), right?

Yes. I have added the fix which checks for MAJOR.MINOR.PATCH.
Without some rules like at least MAJOR.MINOR.PATCH should match, it'll be alright. Be we need to fix on at least some rule.
Thanks.

**Review by juntao — APPROVED** [review]
I will merge this PR so that we can update the install docs. I will raise github issues for the remaining two tasks (root privilege check and user local install). Thanks.

**Comment by SAtacker** [comment]
> I will merge this PR so that we can update the install docs. I will raise github issues for the remaining two tasks (root privilege check and user local install). Thanks.

Thanks !

**Comment by hydai** [comment]
This is fantastic! Thanks @SAtacker :-)

**Pull request merged**
