### PR TITLE
[Docs] Add Japanese README

### PR DESCRIPTION
**Pull request by eltociear**
I created Japanese translated README.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by dannypsnl** [comment]
Thanks, but you will need to add "Signed-Off <email>" in commit message.

**Comment by hydai** [comment]
DCO Ref: https://www.secondstate.io/articles/dco/

**Review by hydai — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
