### PR TITLE
[Docs] Update GOVERNANCE.md

### PR DESCRIPTION
**Pull request by alabulei1**
Calling for all maintainers to vote on updating the Governance.md

Context: Following the suggestion from CNCT ToC Davanum Srinivas, it's better to add a [Maintainer Council](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md) for the WasmEdge Runtime project.

DO NOT MERGE until all the maintainers vote.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by juntao — APPROVED** [review]
LGTM

**Review by hydai — APPROVED** [review]
LGTM

**Review by MediosZ — APPROVED** [review]
LGTM

**Review by dannypsnl — APPROVED** [review]

**Review by hangedfish — APPROVED** [review]
LGTM

**Review by SAtacker — APPROVED** [review]

**Review by q82419 — APPROVED** [review]

**Review by O3Ol — APPROVED** [review]

**Review by ibmibmibm — APPROVED** [review]

**Comment by hydai** [comment]
@alabulei1 
It seems like all maintainers are voted on. Should we process the merge now?

**Comment by alabulei1** [comment]
Yes. Please merge this PR.

**Pull request merged**
