### PR TITLE
[Utils] Scripts:MacOS support

### PR DESCRIPTION
**Pull request by SAtacker**
* Added support for macOS 
* Suggestions given at #433

### CODE REVIEW

**Comment by SAtacker** [comment]
Testing
Installation
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/macos_support/utils/install.sh | bash
```

```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/macos_support/utils/install.sh | bash -s -- -e all
```

Uninstallation
```bash
bash <(wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/macos_support/utils/uninstall.sh)
```

```bash
bash <(wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/macos_support/utils/uninstall.sh) -q
```

**Comment by juntao** [comment]
I tried it on a Mac without LLVM. It tried to `brew install llvm`, but once brew is done, the installer exits.

I think we should simply check for LLVM, and it is not available, just ask the user to run `brew install llvm` themselves, and exit.

**Comment by juntao** [comment]
I tested on a Mac. It seems that the Mac needs to put the `env` line into several more places as newer Macs use zsh instead of bash.

* .bash_profile
* .zshrc
* .zprofile

**Comment by SAtacker** [comment]
The latest commit detects the shell and puts it in the right configuration file
Except for fish, others should be working fine right now.
In my VM it gets written to .zshrc and . profile.

**Comment by juntao** [comment]
Thanks. Currently, on Mac, if I start a new shell after install, it will not be able to find `wasmedge`. I think we need to use shell-specific profile files instead of the simple `.profile`. For example:

* `.bash_profile` for bash
* `.zprofile` for zsh

The reason is that if `.bash_profile` is present, the system would not read `.profile`.

See 

https://stackoverflow.com/questions/7780030/how-to-fix-terminal-not-loading-bashrc-on-os-x-lion
https://www.baeldung.com/linux/bashrc-vs-bash-profile-vs-profile

**Comment by SAtacker** [comment]
Thanks, @juntao for this.
Commit on the way

**Review by juntao — APPROVED** [review]
I tested and it looks good now.

**Pull request merged**
