### PR TITLE
Added the C++ example to the book

### PR DESCRIPTION
**Pull request by TheZal**
This pr is related to #1865

### CODE REVIEW

**Review by hydai — CHANGES_REQUESTED** [review]
This file needs to have more information.
1. This file doesn't describe what kind of application is used for the demo.
2. This file doesn't explain the details of the example.
3. This file doesn't make readers know how to archive this.

A good tutorial should contain the following information:
1. How to set up the environment with detailed steps.
2. What to implement the basic functionality.

**Comment by Vishvsalvi** [comment]
> 1. How to set up the environment with detailed steps.
> 2. What to implement the basic functionality.

I can help you with the 1st part, may I ?

**Comment by TheZal** [comment]
I'm really sorry but right now I can't work on that anymore... you can assign it to someone else, sry!

**Comment by hydai** [comment]
> I can help you with the 1st part, may I ?

Welcome :-)

**Comment by hydai** [comment]
Hi @Vishvsalvi,
Could you please leave comments under #1865? So I can assign the issue to you.

Hi @TheZal,
Thanks for your previous contribution; I am closing this PR.

**Pull request closed without merging**
