### PR TITLE
[Docs] Document the example of wasmedge-sys APIs

### PR DESCRIPTION
**Pull request by apepkuss**
This PR is to add tutorial files for `wasmedge-sys`. The files include two different formats for different purposes:

- The markdown format is added to WasmEdge docs as a part of the mdbook.
- The evcxr_jupyter notebook is for experimenting with the APIs directly, and added as part of the wasmedge-sys examples.

### CODE REVIEW

**Comment by juntao** [comment]
My guess is that the quick start should be in the book?

**Comment by apepkuss** [comment]
> My guess is that the quick start should be in the book?

Hi @juntao, yes, you're right. All the contents in the markdown format will finally be added to the relevant sections of the mdbook when we prepare enough cases for the tutorial. For now, it just has one demo case, so keep it in the docs directory temporarily, in case anyone is interested in it.

**Comment by juntao** [comment]
Yes. I would prefer to have the book as a single source of truth. The issue with having docs in the project is that ppl might bookmark it and we will need to maintain two docs for a long time.

**Comment by juntao** [comment]
Yes, code-related artifacts, such as the notebook, could be located together with the code. You can refer to it from the MDBOOK pages if needed.

**Review by hydai — CHANGES_REQUESTED** [review]
Please use spelling and grammar checking tools on the document. E.g. grammarly.com.

**Review by hydai — APPROVED** [review]

**Pull request merged**
