### PR TITLE
changed .dylib to .framework

### PR DESCRIPTION
**Pull request by 836hardik-agrawal**
According to what i understand. I have tried to solve the problem as directed by @hydai by looking the cmake files.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by lazyperson1020** [comment]
@836hardik-agrawal I think  we need to change the code in such a manner that the framework is built in the /System/Library/Frameworks for the macos.

**Comment by 836hardik-agrawal** [comment]
@lazyperson1020 .I checked the cmake files,but not able to get what it meant by changing code in manner framework is built in 
System/Library/Frameworks for the macos.

**Comment by hydai** [comment]
I don't think this is the correct way to implement this feature.

1. We want to provide an option for users that they can choose `dylib` or the new `framework` format.
2. This only replaces the `dylib` with `framework`, which is nonsense.
3. We want to provide `.framework` for all `dylib`, not the `wasi-nn` related ones.

**Comment by 836hardik-agrawal** [comment]
> Hi @836hardik-agrawal Are you going to implement this feature?

Sorry not able to understand and not able to do it .

**Pull request closed without merging**
