### PR TITLE
[nix] flake update and use llvm18

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
Could we try llvm19?

**Comment by dannypsnl** [comment]
Sure.

**Comment by dannypsnl** [comment]
@hydai I check the nix channel, we are using stable (24.05), where latest is 18, to use 19 will need to use unstable channel.

**Comment by hydai** [comment]
No problem. Then let's use llvm18 for now.

**Pull request merged**
