### PR TITLE
[CI] Build CUDA related plugins

### PR DESCRIPTION
**Pull request by dm4**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by 0yi0 — COMMENTED** [review]
I don't see why need array and for loops here?

**Comment by dm4** [comment]
> I don't see why need array and for loops here?

I was thinking that for convenience for other plugins needing CUDA in the future, it might be easier to modify. Or do you think keeping it simple here is better?

**Comment by dm4** [comment]
@hydai Do you think other things will soon use CUDA as well? If not, I'll just implement it simply here.

**Comment by hydai** [comment]
Due to the frequent updates of the llama.cpp. I think it should be fine to have stable diffusion here. WDYT?

**Review by 0yi0 — APPROVED** [review]

**Pull request merged**
