### PR TITLE
[Rust] Removed standalone mode

### PR DESCRIPTION
**Pull request by apepkuss**
In this PR, the `standalone` mode is removed from the `bindings-rust` workflow. In addition, the build script is also refactored to remove the unused functions.

### CODE REVIEW

**Comment by apepkuss** [comment]
Hi @hydai, could you please help review this PR? Thanks a lot!

**Review by hydai — APPROVED** [review]

**Comment by apepkuss** [comment]
@hydai Rebased on the latest master branch. Thanks!

**Comment by apepkuss** [comment]
@hydai Please merge #1592 before this PR. Thanks!

**Comment by hydai** [comment]
Hi @apepkuss 
I would like to check if we want to remove the standalone mode completely. Or do we just want to remove this mode from the CI workflow?

**Comment by hydai** [comment]
Looks like the llvm is upgraded to 14. And the namespace of `mach_o` is replaced by `macho`. A fixed PR is sent: #1601

**Comment by hydai** [comment]
I found the previous workflow is using `llvm 13.0.1`: https://github.com/WasmEdge/WasmEdge/runs/7090463905?check_suite_focus=true#step:3:13
However, the latest workflow is using `llvm 14.0.6`: https://github.com/WasmEdge/WasmEdge/runs/7094097580?check_suite_focus=true#step:6:42

**Comment by hydai** [comment]
I will merge this after #1601 is merged.

**Comment by apepkuss** [comment]
> I will merge this after #1601 is merged.

Got it! Thanks a lot!

**Review by hydai — APPROVED** [review]

**Comment by apepkuss** [comment]
@hydai Thanks for the review!

**Pull request merged**
