### PR TITLE
Add GitHub action to submit MSI package to WinGet repositories

### PR DESCRIPTION
**Pull request by abhinandanudupa**
Credits:

- https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

Please ensure that necessary permissions are granted the the GitHub token being used here, refer - https://github.com/microsoft/winget-create#github-personal-access-token-classic-permissions

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by abhinandanudupa** [comment]
@hydai Do I need to change something in the PR?

**Comment by hydai** [comment]
Hi @abhinandanudupa 
Because it asks for the `GitHub_Token`, I am checking if there is any potential issue inside these workflows. It may take time to ensure everything is fine.

**Comment by abhinandanudupa** [comment]
> Hi @abhinandanudupa Because it asks for the `GitHub_Token`, I am checking if there is any potential issue inside these workflows. It may take time to ensure everything is fine.

Understood

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Thanks

**Pull request merged**
