### PR TITLE
[Docs] Add self assessment document

### PR DESCRIPTION
**Pull request by dm4**
This self assessment document is for TSSA process.
The TSSA issue is at https://github.com/cncf/tag-security/issues/1337

Since the links in this document is depend on documents in PR https://github.com/WasmEdge/WasmEdge/pull/3472, this PR should merge after PR https://github.com/WasmEdge/WasmEdge/pull/3472.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

**Review by hydai — APPROVED** [review]
LGTM. I am calling the maintainers to review this document.

/cc @juntao @ibmibmibm @q82419 @hydai

**Review by ibmibmibm — APPROVED** [review]

**Comment by ibmibmibm** [comment]
LGTM.

**Comment by q82419** [comment]
LGTM.

**Comment by hydai** [comment]
Since 3/4 of the maintainers approved this, I am merging it after the CI is green.

**Pull request merged**
