### PR TITLE
[Plugin] Stable Diffusion: Upgrade to 9578fdc

### PR DESCRIPTION
**Pull request by grorge123**
For #3905

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
@grorge123 
It failed on mac metal, please take a look.

**Comment by grorge123** [comment]
> @grorge123 It failed on mac metal, please take a look.

It is because of the GGML API change. I have raised the issue to the upstream. I will update when sd merges the fixed patch.

**Comment by hydai** [comment]
I see. Thanks.

**Comment by alabulei1** [comment]
Does it work on Ubuntu?

**Comment by hydai** [comment]
Yes. It only failed on mac metal now.

**Pull request merged**
