### PR TITLE
permissions added for workflow files

### PR DESCRIPTION
**Pull request by jaydee029**
For issue #2979 
Permissions for following files added
- IWYU-scan
- build.yml
- build-extensions.yml
- build_for_riscv.yml
- wasi-testsuite.yml

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by hydai — APPROVED** [review]

**Comment by jaydee029** [comment]
hey @hydai this pr was failing a few tests after editing those workflows, i'm not sure about those.

**Comment by hydai** [comment]
The java workflows is expected to fail due to the API incompatible.
The WASI-Testsuite is related to this issue: https://github.com/WasmEdge/WasmEdge/issues/3062

That's known issue.

**Comment by jaydee029** [comment]
oh okay, i didn't realize that. Thanks.

**Pull request merged**
