### PR TITLE
[Rust]: Fix errors in examples.

### PR DESCRIPTION
**Pull request by EmisonLu**
Fix errors in `hostfunc.rs` and `hostfunc2.rs`.

### CODE REVIEW

**Comment by apepkuss** [comment]
@EmisonLu Please rebase this PR onto the latest master. Thanks!

**Comment by hydai** [comment]
@apepkuss  PTAL

**Comment by hydai** [comment]
Hi @apepkuss 
Do these errors still live in the examples? Should we go ahead and merge it? Or is this already invalid?

**Comment by apepkuss** [comment]
@hydai The errors are still open in these two examples.

**Review by apepkuss — DISMISSED** [review]

**Comment by apepkuss** [comment]
@EmisonLu Could you please rebase this PR onto the latest master branch? Thanks!

**Comment by EmisonLu** [comment]
@apepkuss I have rebased this PR.

**Comment by apepkuss** [comment]
> @apepkuss I have rebased this PR.

Thanks a lot!

**Review by apepkuss — APPROVED** [review]

**Review by hydai — APPROVED** [review]

**Pull request merged**
