### PR TITLE
[Utils] Uninstall script improvements

### PR DESCRIPTION
**Pull request by SAtacker**
- [X] Detects `wasmedge` as per #389 
- [x] Uninstall.txt

### CODE REVIEW

**Comment by SAtacker** [comment]
Using `UNINSTALL.txt` for tracking installation files will be a workaround. IMO it's too much to rely on the bin directory and assume there will be an `UNINSTALL.txt` present. And in the case of `/usr/local` installations, it'll be a bit non-standard to do so.
Currently, it locates the `wasmedge` bin as you mentioned but I am feeling a bit odd about creating an `UNINSTALL.txt`

**Comment by juntao** [comment]
I am open to suggestions. :) Can you research how other projects handle uninstall?

**Comment by SAtacker** [comment]
> I am open to suggestions. :) Can you research how other projects handle uninstall?

Homebrew does this by making a list inside `/tmp/uninstall.PID` and then asks if they want to do so as mentioned at https://github.com/WasmEdge/WasmEdge/issues/412#issuecomment-919465690.

Currently, this uninstall script detects if `wasmedge` binaries are found on `PATH` and if not it looks for `$HOME/.wasmedge` if the binary is found there then it detects that as the installation path and if not, exits.
Further, all the files that we need to uninstall as per extensions are hardcoded into the script.

**Comment by juntao** [comment]
The hardcoded uninstall list will not work once we have several versions of WasmEdge. So, I guess we do need to maintain an UNINSTALL list.

**Comment by SAtacker** [comment]
> The hardcoded uninstall list will not work once we have several versions of WasmEdge. So, I guess we do need to maintain an UNINSTALL list. 

Yes, I agree with it. But where do we keep this list? Are you suggesting that we modify the `install.sh` to output a list of whatever files are installed into some standard directory like `$HOME/. wasmedge` and a safe fallback in case such a list is deleted unintentionally by the user?

**Comment by juntao** [comment]
Perhaps we can keep a list of files as comments in the `env` file? You can always find the file at `../env` from the wasmedge executable. The uninstall script can parse the `env` file's comments section and decide which files to remove.

If the `env` file is not available, the uninstall script should print an error message and exit.

**Comment by SAtacker** [comment]
Hi, am back here. Will try to complete this today itself.

**Comment by SAtacker** [comment]
Install
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/uninstall_script/utils/install.sh | bash -s -- -e all
```
Uninstall
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/uninstall_script/utils/uninstall.sh | bash -s -- -q
```
Without the `-q` it runs infinitely, a bit of an issue right now

**Comment by SAtacker** [comment]
Install
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/uninstall_script/utils/install.sh | bash -s -- -e all
```
Uninstall Non-Interactive
```bash
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/uninstall_script/utils/uninstall.sh | bash -s -- -q
```
Uninstall Interactively
```bash
bash <(wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/uninstall_script/utils/uninstall.sh)
```

**Comment by juntao** [comment]
I think the uninstall script should just remove the files in `env`. There is no need to attempt to remove the parent directories unless they are empty. It is okay to leave empty directories. For example, currently, the script removes other files from `/usr/local` when I install there.

```
Removing /usr/local/env
Removing /usr/local/games
Removing /usr/local/share/man
Removing /usr/local/share/ca-certificates
Removing /usr/local/src
Removing /usr/local/lib
Removing /usr/local/bin
Removing /usr/local/include
Removing /usr/local/etc
```

**Comment by SAtacker** [comment]
How about I do that only for default path `$HOME/.wasmedge` ?

**Comment by SAtacker** [comment]
Could you please review @juntao ?

**Review by juntao — DISMISSED** [review]
Looks good

**Review by juntao — DISMISSED** [review]
I made some changes to the docs

**Comment by hydai** [comment]
@juntao your commit message should have a tag such as `[Docs] ` when you modified the documents. Just like @SAtacker has put the `[Utils] ` in his commit messages.

**Comment by juntao** [comment]
Done

> @juntao your commit message should have a tag such as `[Docs] ` when you modified the documents. Just like @SAtacker has put the `[Utils] ` in his commit messages.

**Comment by hydai** [comment]
CleanShot 2021-09-30 at 11 23 51@2x

Seems like not right. You do not modify your origin one, however, you add two more commits.

**Comment by juntao** [comment]
Hmm, how about now?

**Pull request merged**
