### PR TITLE
[Docs] Translate embed/go.md to zh #1094

### PR DESCRIPTION
**Pull request by jerbmarx**
Signed-off-by: jerbmarx <jerbmarx@foxmail.com>

### CODE REVIEW

**Comment by alabulei1** [comment]
@jerbmarx  Thanks for your contribution! However, I found some issues exited in the English Verison. Please refer to #1170 for the improved English Version.

**Comment by jerbmarx** [comment]
> @jerbmarx Thanks for your contribution! However, I found some issues exited in the English Verison. Please refer to #1170 for the improved English Version.

I have updated this reference to #1170. Please have a review. Thanks a lot!

**Comment by alabulei1** [comment]
@jerbmarx  Thanks. But there are still two pending feedbacks. Could you check out again?

**Comment by jerbmarx** [comment]
> @jerbmarx Thanks. But there are still two pending feedbacks. Could you check out again?

@alabulei1  Of course. Please provide reference links as soon as possible when these feedbacks are solved. Thanks a lot.

**Comment by alabulei1** [comment]
> > @jerbmarx Thanks. But there are still two pending feedbacks. Could you check out again?
> 
> @alabulei1 Of course. Please provide reference links as soon as possible when these feedbacks are solved. Thanks a lot.

**Comment by jerbmarx** [comment]
@alabulei1 I have updated it again. Could you review it again? Thank you very much.

**Comment by alabulei1** [comment]
LGTM!

@hydai  Could you help merge this PR?

**Pull request merged**
