### PR TITLE
[WIP] Make WasmEdge on macos statically link llvm

### PR DESCRIPTION
**Pull request by hydai**
Signed-off-by: hydai <hydai@secondstate.io>

### CODE REVIEW

**Comment by hydai** [comment]
I am creating the [llvm-macos repo](https://github.com/hydai/llvm-macos) to build the llvm 14.0.6 from scratch to make sure it only relies on the AppleClang and XCode SDK.

**Comment by q82419** [comment]
This can be replaced by #1698 .

**Comment by q82419** [comment]
I think this is not more needed?

**Comment by hydai** [comment]
Yup. Closing this.

**Pull request closed without merging**
