### PR TITLE
[WASI-NN] Add GPU target support for pytorch backend.

### LINKED ISSUE #2140: [WASI-NN] PyTorch backend doesn't support GPU version
### Current State

WasmEdge only supports :libtorch-1.8.0~1.8.2-cpu.

WasmEdge does not support :
* libtorch-1.7.1-cpu 
* libtorch-1.9.0-cpu 
* libtorch-1.7.1~1.9.0-cuda

In summary,  WasmEdge does not support pytorch operations on GPU, only on CPU.

### Expected

WasmEdge both supports pytorch operations on CPU and  <font color='red'>**on GPU**</font>.

## Environment

- Hardware Architecture: x86_64
 
- Operating system:  Ubuntu 22.04.1 LTS

- NVIDIA-SMI：   Driver Version: 450.203.03   CUDA Version: 11.0 

- C++ Compiler version:  g++ 11.3.0

- Boost version:1.74.0

- wasmedge version: 0.11.2

## Steps to Reproduce

*WasmEdge runs pytorch task smooth on CPU but can not on GPU.*

load libtorch-one_version-cpu:
```
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.0-cpu/lib
# or
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.1-cpu/lib
# or
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.2-cpu/lib
```

then WasmEdge runs pytorch task:
```
$ cd ~/wasmedge-example/pytorch/
$ wasmedge --dir .:. out.wasm mobilenet.pt input.jpg
```

the task can smoothly run:
```
Read torchscript binaries, size in bytes: 14376860
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
Executed graph inference
   1.) [954](20.6681)banana
   2.) [940](12.1483)spaghetti squash
   3.) [951](11.5748)lemon
   4.) [950](10.4899)orange
```

```
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.1-cuda/lib
# any versions of cuda-based libtorch can not support the same pytorch task.
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.9.0-cpu/lib
# # other versions of cpu-based libtorch can not support the same pytorch task.
```

then WasmEdge runs the same pytorch task after setting different version libtorch or cuda-based libtorch:
```
$ cd ~/wasmedge-example/pytorch/
$ wasmedge --dir .:. out.wasm mobilenet.pt input.jpg
```

the task got error:
```
Read torchscript binaries, size in bytes: 14376860
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
wasmedge: symbol lookup error: /usr/local/lib/wasmedge/libwasmedgePluginWasiNN.so: undefined symbol: _ZNK5torch3jit6Object11find_methodERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

** My hypothesis is that WasmEdge is not able to support pytorch（/tensorflow） operations on GPU or not compatible to cuda-based libtorch. **

Looking foward to your solution! Thank you!

### PR DESCRIPTION
**Pull request by yanghaku**
This PR adds GPU target support for the WASI-NN Pytorch backend to speed up deep learning inference. 

To use the GPU target, there are 3 requirements:
1. Hardware:  Nvidia GPUs which support CUDA, AMD GPUs which support ROCM.
2. Runtime: ```libtorch.so``` must be built with CUDA/ROCM support.
3. User Code:  Users should select the ```GPU``` target when loading the graph.

Fix #2140

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by juntao** [comment]
Flows review

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by q82419** [comment]
Looks great.

@gusye1234  can you help to double confirm this? Thanks!

**Review by hydai — APPROVED** [review]

**Comment by 17862687921** [comment]
The previous examples of wasi-nn-pytorch were based on CPU, now wasi-nn-pytorch has been updated to support GPU. Could you please provide a GPU related testing example for validation and learning?

**Pull request merged**
