### PR TITLE
[CI] Refactored workflows related to Rust bindings for releasing docs

### PR DESCRIPTION
**Pull request by apepkuss**
In this PR, the `rust-wasmedge-sys-docs` and `rust-wasmedge-types-docs` workflows are removed. The `rust-wasmedge-sdk-docs` workflow is responsible for docs publishing.

### CODE REVIEW

**Comment by apepkuss** [comment]
Hi @hydai, could you please help review this PR? Thanks a lot!

**Comment by hydai** [comment]
The release CI should be refactoring either:
https://github.com/WasmEdge/WasmEdge/runs/7575954698?check_suite_focus=true

It depends on the `sys`, but it doesn't release in order.

**Comment by apepkuss** [comment]
> Another thing is whether the document of `types` and `sys` will be published via `sdk` or not. I found you just remove `types` and `sys`. But there is not uploaded phase in the `sdk` one.

`sdk` depends on `sys` and `types`, so their docs will be published together.

**Comment by apepkuss** [comment]
> 

The correct order of publishing the three crates should be `types` first, then `sys`, and the last one `sdk`. Could you please try to publish them in this order on your side?

**Pull request closed without merging**
