### PR TITLE
Installer v2: Install wasi-logging by default and deprecate rustls

### PR DESCRIPTION
**Pull request by hydai**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

**Review by juntao — APPROVED** [review]
LGTM

**Review by juntao — COMMENTED** [review]
But the CI failed ...

**Comment by hydai** [comment]
We don't have wasi-logging for Intel Mac when 0.13.5 is released. Let me build the release assets manually.

**Pull request merged**
