### PR TITLE
[Rust] Supported the thread-safe feature

### PR DESCRIPTION
**Pull request by apepkuss**
This PR is to implement Send and Sync traits for the structs in `wasmedge-sys`.

### CODE REVIEW

**Comment by apepkuss** [comment]
Hi @hydai, could you please help review this PR? Thanks a lot!

**Comment by apepkuss** [comment]
@hydai Please help review this PR. Thanks a lot!

**Review by hydai — CHANGES_REQUESTED** [review]
Because there are several breaking changes. Please bump the version.

**Comment by apepkuss** [comment]
@hydai The version has already changed to v0.4.0.

**Review by hydai — APPROVED** [review]

**Comment by apepkuss** [comment]
@hydai Thank you very much for the review.

**Pull request merged**
