### PR TITLE
[CI] Add workflow to test rust bindings on Windows

### PR DESCRIPTION
**Pull request by abhinandanudupa**
The workflow tests rust bindings on windows -
1. In the standalone mode
2. By specifying the WASMEDGE_BUILD_DIR variable

Resolves issue: #1504

### CODE REVIEW

**Comment by hydai** [comment]
Hi @apepkuss 
@abhinandanudupa has added the Windows workflow which is based on our Linux/macOS ones. However, it looks like wasmedge-sys always failed on the Windows platform. Could you please help with this? I am not sure if there is a bug in our Windows part of wasmedge-sys or is a bug related to the workflow directly.

**Comment by apepkuss** [comment]
> Hi @apepkuss @abhinandanudupa has added the Windows workflow which is based on our Linux/macOS ones. However, it looks like wasmedge-sys always failed on the Windows platform. Could you please help with this? I am not sure if there is a bug in our Windows part of wasmedge-sys or is a bug related to the workflow directly.

@hydai I'll check the issue and feedback here asap. Thanks!

**Comment by apepkuss** [comment]
@hydai A linking error was raised when building `WasmEdge`. It seems related to plugins. Do you have any idea about how to fix it? As a reference, in case, the entire log of the CI workflow can be found [here](https://github.com/apepkuss/WasmEdge-1/runs/6767211091?check_suite_focus=true). Thanks!

```
[133/163] Linking CXX shared library plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.dll
FAILED: plugins/wasmedge_process/wasmedgePluginWasmEdgeProcess.dll plugins/wasmedge_process/wasmedgePluginWasmEdgeProcess.lib
cmd.exe /C "cd . && "C:\\Program Files\\CMake\\bin\\cmake.exe" -E vs_link_dll --intdir=plugins\\wasmedge_process\\CMakeFiles\\wasmedgePluginWasmEdgeProcess.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\LLVM\\bin\\lld-link.exe /nologo plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processenv.cpp.obj plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processfunc.cpp.obj plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processmodule.cpp.obj  /out:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.dll /implib:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.lib /pdb:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO  lib/common/wasmedgeCommon.lib  lib/system/wasmedgeSystem.lib  lib/common/wasmedgeCommon.lib  _deps/spdlog-build/spdlog.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK: command "C:\\PROGRA~1\\LLVM\\bin\\lld-link.exe /nologo plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processenv.cpp.obj plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processfunc.cpp.obj plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processmodule.cpp.obj /out:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.dll /implib:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.lib /pdb:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO lib/common/wasmedgeCommon.lib lib/system/wasmedgeSystem.lib lib/common/wasmedgeCommon.lib _deps/spdlog-build/spdlog.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:plugins\\wasmedge_process\\wasmedgePluginWasmEdgeProcess.dll.manifest" failed (exit code 1) with the following output:
lld-link: error: undefined symbol: public: __cdecl WasmEdge::Plugin::PluginRegister::PluginRegister(struct WasmEdge::Plugin::Plugin::PluginDescriptor const *)
>>> referenced by D:/a/WasmEdge-1/WasmEdge-1/bindings/rust/target/debug/build/wasmedge-sys-f124e049724be280/out/wasmedge/plugins/wasmedge_process/processenv.cpp
>>>               plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processenv.cpp.obj

lld-link: error: undefined symbol: public: __cdecl WasmEdge::Plugin::PluginRegister::~PluginRegister(void)
>>> referenced by D:/a/WasmEdge-1/WasmEdge-1/bindings/rust/target/debug/build/wasmedge-sys-f124e049724be280/out/wasmedge/plugins/wasmedge_process/processenv.cpp
>>>               plugins/wasmedge_process/CMakeFiles/wasmedgePluginWasmEdgeProcess.dir/processenv.cpp.obj
```

As a reference, the step in the CI workflow related to the failure is shown below:
```
- name: Test wasmedge-sys in standalone mode
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64 -winsdk=10.0.19041.0"
          $llvm = "LLVM-13.0.1-win64.zip"
          curl -sLO https://github.com/WasmEdge/llvm-windows/releases/download/llvmorg-13.0.1/LLVM-13.0.1-win64.zip -o $llvm
          Expand-Archive -Path $llvm
          $Env:CC = "clang-cl"
          $Env:CXX = "clang-cl"
          cd bindings/rust/
          $WASMEDGE_DIR="$(pwd)/../../"
          cargo +nightly test -p wasmedge-sys --lib --examples --features standalone
          cargo +nightly test -p wasmedge-sys --doc

```

**Comment by hydai** [comment]
Hi @apepkuss 
I would like to know how does the wasmedge-sys build wasmedge? You can find the WasmEdge is built successfully in the master branch: https://github.com/WasmEdge/WasmEdge/runs/6750390823?check_suite_focus=true#step:5:349

**Comment by apepkuss** [comment]
> Hi @apepkuss I would like to know how does the wasmedge-sys build wasmedge? You can find the WasmEdge is built successfully in the master branch: https://github.com/WasmEdge/WasmEdge/runs/6750390823?check_suite_focus=true#step:5:349

@hydai Yes, I referenced both the script of the `build_windows` job in `build.yml` and the relevant section of `WasmEdge Book`. The following code is part of the build script of `wasmedge-sys`, which is relevant to the compilation.

```rust
// D:\a\WasmEdge-1\WasmEdge-1\bindings\rust\wasmedge-sys
    let curr_dir = env::current_dir().unwrap();
    println!(
        "cargo:warning=[wasmedge-sys] current dir: {}",
        curr_dir.display()
    );
    // D:\a\WasmEdge-1\WasmEdge-1
    let root_dir = curr_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    println!(
        "cargo:warning=[wasmedge-sys] root_dir: {}",
        root_dir.display()
    );

    // set the path to the llvm dir
    let llvm_dir = root_dir
        .join("LLVM-13.0.1-win64")
        .join("LLVM-13.0.1-win64")
        .join("lib")
        .join("cmake")
        .join("llvm");
    assert!(llvm_dir.exists());
    println!(
        "cargo:warning=[wasmedge-sys] llvm_dir: {}",
        llvm_dir.display()
    );
    let llvm_dir_s = format!("-DLLVM_DIR={}", llvm_dir.to_str().unwrap());
    println!("cargo:warning=[wasmedge-sys] -DLLVM_DIR: {}", &llvm_dir_s);

    let output = Command::new("cmake")
        .current_dir(wasmedge_dir.as_ref())
        .args([
            "-Bbuild",
            "-GNinja",
            "-DCMAKE_BUILD_TYPE=Release",
            #[cfg(not(feature = "aot"))]
            "-DWASMEDGE_BUILD_AOT_RUNTIME=OFF",
            r#"-DCMAKE_SYSTEM_VERSION="10.0.19041.0""#,
            "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL",
            llvm_dir_s.as_str(),
            "-DWASMEDGE_BUILD_TESTS=ON",
            r#"-DWASMEDGE_BUILD_PACKAGE="ZIP""#,
            ".",
        ])
        .output()
        .expect("[wasmedge-sys] fail to cmake setup wasmedge project");
    println!(
        "cargo:warning=[wasmedge-sys] cmake -Bbuild -GNinja ...: {:?}",
        output,
    );

    let output = Command::new("cmake")
        .current_dir(wasmedge_dir.as_ref())
        .args(["--build", "build"])
        .output()
        .expect("[wasmedge-sys] fail to cmake build wasmedge project");
    println!(
        "cargo:warning=[wasmedge-sys] cmake --build build: {:?}",
        output
    );
```

**Comment by apepkuss** [comment]
I don't have a Windows machine nearby, so a little hard to debug the issue 😄

**Comment by hydai** [comment]
> I don't have a Windows machine nearby, so a little hard to debug the issue 😄

Maybe we can have a verbose mode and print it on the CI workflow?

**Comment by apepkuss** [comment]
> > I don't have a Windows machine nearby, so a little hard to debug the issue 😄
> 
> Maybe we can have a verbose mode and print it on the CI workflow?

I think it could be the only way in the current situation.

**Comment by hydai** [comment]
Since there are some issues that need to be resolved on the Windows platform. I would like to merge this PR first and create another issue for tracking the wasmedge-sys building issue on the Windows platform.

**Comment by hydai** [comment]
Just created #1527.

**Comment by abhinandanudupa** [comment]
@hydai I think forgot to ask you about this:
```
- name: Test wasmedge-sys in standalone mode
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64 -winsdk=10.0.19041.0"
          $llvm = "LLVM-13.0.1-win64.zip"
          curl -sLO https://github.com/WasmEdge/llvm-windows/releases/download/llvmorg-13.0.1/LLVM-13.0.1-win64.zip -o $llvm
          Expand-Archive -Path $llvm
          $Env:CC = "clang-cl"
          $Env:CXX = "clang-cl"
          cd bindings/rust/
          $WASMEDGE_DIR="$(pwd)/../../"
          cargo +nightly test -p wasmedge-sys --lib --examples --features standalone
          cargo +nightly test -p wasmedge-sys --doc

```

Downloading and setting a path to `LLVM` is not necessary right? And what about setting the compilers? Setting those is needed in-case `clang-cl` is not chosen right?

**Comment by hydai** [comment]
Well, the standalone one will need to build wasmedge by itself, so I believe installing and setup the llvm and clang-cl are nesessary.

**Review by hydai — APPROVED** [review]

**Comment by apepkuss** [comment]
@hydai Could you please help with the linking error above from @spencergotowork? Thanks!

**Comment by ibmibmibm** [comment]
Checked with newest master version of wasmedge on windows, Didn't occurs this error.

**Pull request merged**
