### PR TITLE
[Rust] Expose ImportType and ExportType; Implement new APIs for Module

### LINKED ISSUE #684: [Rust SDK] WasmEdge_ASTModuleListExports

### LINKED ISSUE #685: [Rust SDK] WasmEdge_ASTModuleListExportsLength

### LINKED ISSUE #686: [Rust SDK] WasmEdge_ASTModuleListImports

### LINKED ISSUE #687: [Rust SDK] WasmEdge_ASTModuleListImportsLength

### LINKED ISSUE #710: [Rust SDK] WasmEdge_ExportTypeGetExternalName

### LINKED ISSUE #711: [Rust SDK] WasmEdge_ExportTypeGetExternalType

### LINKED ISSUE #712: [Rust SDK] WasmEdge_ExportTypeGetFunctionType

### LINKED ISSUE #713: [Rust SDK] WasmEdge_ExportTypeGetGlobalType

### LINKED ISSUE #716: [Rust SDK] WasmEdge_ExportTypeGetMemoryType

### LINKED ISSUE #718: [Rust SDK] WasmEdge_ExportTypeGetTableType

### LINKED ISSUE #724: [Rust SDK] WasmEdge_ExportTypeGetTableType

### LINKED ISSUE #753: [Rust SDK] WasmEdge_ImportTypeGetExternalName

### LINKED ISSUE #755: [Rust SDK] WasmEdge_ImportTypeGetExternalType

### LINKED ISSUE #756: [Rust SDK] WasmEdge_ImportTypeGetFunctionType

### LINKED ISSUE #757: [Rust SDK] WasmEdge_ImportTypeGetGlobalType

### LINKED ISSUE #758: [Rust SDK] WasmEdge_ImportTypeGetMemoryType

### LINKED ISSUE #759: [Rust SDK] WasmEdge_ImportTypeGetModuleName

### LINKED ISSUE #760: [Rust SDK] WasmEdge_ImportTypeGetTableType

### PR DESCRIPTION
**Pull request by apepkuss**
The following C-APIs are involved in this PR:
- ImportType
  - Fix #755 
  - Fix #759 
  - Fix #753 
  - Fix #756 
  - Fix #760 
  - Fix #758 
  - Fix #757 
- ExportType
  - Fix #710 
  - Fix #711 
  - Fix #712 
  - Fix #713 
  - Fix #716 
  - Fix #718 
  - Fix #724 
- ASTModule
  - Fix #687 
  - Fix #686 
  - Fix #685 
  - Fix #684

### CODE REVIEW

**Comment by apepkuss** [comment]
Hi @yanganto  and @hydai, Could you please help review this PR? Thanks a lot!

**Review by yanganto — APPROVED** [review]

**Comment by hydai** [comment]
Please update `types.rs`. It has conflicts again due to the latest merged PR :-)

**Comment by apepkuss** [comment]
@hydai, I'll resolve the conflicts, thanks a lot!

**Comment by apepkuss** [comment]
Hi @hydai, the conflicts have been resolved, please review the latest commit again, thanks a lot!

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Looks like GitHub broken again...
This PR is merged: https://github.com/WasmEdge/WasmEdge/commit/0f821faa8f1310481e027c639695d602fa1dbd62
However, it doesn't show this got merged. I am closing this manually.

**Pull request closed without merging**
