### PR TITLE
[Docker] Disable pytorch c++11 abi on manylinux_2_28

### PR DESCRIPTION
**Pull request by LFsWang**
for #3724

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by q82419** [comment]
> for #4147

@LFsWang cannot find this issue number?

**Comment by q82419** [comment]
Related to #3827

**Comment by LFsWang** [comment]
> > for #4147
> 
> @LFsWang cannot find this issue number?

fixed

**Review by hydai — APPROVED** [review]

**Pull request merged**
