### PR TITLE
[Install Script] Improve Install script

### PR DESCRIPTION
**Pull request by SAtacker**
- [X] Remove `apt`/`deb` deps #384 
  - Checks for `git` and if not available then exits.
  - Checks for `wget`, if not then checks for `curl`, if not then exits.
- [X] #390

### CODE REVIEW

**Comment by SAtacker** [comment]
For quick testing of my branch you can use
```sh
wget -qO- https://raw.githubusercontent.com/SAtacker/WasmEdge/remove_apt_deps/utils/install.sh | bash -s -- -e all
```
and then `source $HOME/.wasmedge/env`

**Comment by juntao** [comment]
The Rust installer adds the following line to the end of `$HOME/.profile` so that the user does not have to source the `env` every time he logs in. We should do that too.

```
. "$HOME/.cargo/env"
```

**Comment by SAtacker** [comment]
> The Rust installer adds the following line to the end of `$HOME/.profile` so that the user does not have to source the `env` every time he logs in. We should do that too.
> 
> ```
> . "$HOME/.cargo/env"
> ```

Actually, IMO, we should let the user handle this because sometimes they may not need those in their path. For example, in the future, if we have some library in LD_LIBRARY_PATH that is analogous to one which they already have, it'll mess with their program as every time they open a new terminal it'll still be sourced and linked to ours. `rust` might do that as their is no `lib` inside ~/.cargo/
Do we need to do this?

**Comment by juntao** [comment]
Hmm, that is a good point. However, I do not think we can ask the user to remember to source the env every time they open a new terminal.

When we install in `/usr/local`, we do `ldconfig`, which also has the potential to introduce potential conflicts to existing libraries. Is that correct?

I think this is something we may need to explain in the `install.md` docs. But by default, I think we should run `env` for the user in a new terminal.

**Comment by SAtacker** [comment]
> Hmm, that is a good point. However, I do not think we can ask the user to remember to source the env every time they open a new terminal.
> 
> When we install in `/usr/local`, we do `ldconfig`, which also has the potential to introduce potential conflicts to existing libraries. Is that correct?
> 
> I think this is something we may need to explain in the `install.md` docs. But by default, I think we should run `env` for the user in a new terminal.

Yes. Thanks. I'll make the change.

**Comment by juntao** [comment]
I think we still need to ask the user to do `source $HOME/.wasmedge/env` immediately after the install. The install script runs in its own process. when it exits, the terminal does not retain the path settings.

Also, I'd like to put the `. "$HOME/.wasmedge/env"` line in `.profile` as it is a sh script not a bash specific script. Thanks.

**Comment by SAtacker** [comment]
> I think we still need to ask the user to do `source $HOME/.wasmedge/env` immediately after the install. The install script runs in its own process. when it exits, the terminal does not retain the path settings.
> 
> Also, I'd like to put the `. "$HOME/.wasmedge/env"` line in `.profile` as it is a sh script not a bash specific script. Thanks.

Yes, I'll default it to `.profile` and the latter part too. Thanks

**Comment by juntao** [comment]
Can you fix the DCO? 

https://github.com/WasmEdge/WasmEdge/runs/3552835039

**Comment by SAtacker** [comment]
In case somebody wants to know what I did to fix a commit message 6 commits before then
`git rebase -i HEAD~6` and then `reword` the commit that led to DCO to fail. 
And then I rebased to master to update it. Should have done that before.

**Review by juntao — APPROVED** [review]
This is great. Thank you!

**Pull request merged**
