### PR TITLE
Try to fix java binding

### PR DESCRIPTION
**Pull request by ibmibmibm**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
@ibmibmibm 
Could you rebase to the latest master?

**Review by dannypsnl — APPROVED** [review]

**Comment by dannypsnl** [comment]
The macos 13 fail message: `/Users/ss/workspace/actions-runner/_work/_temp/cf364614-2528-484a-9d09-c2e12dac7786.sh: line 1: brew: command not found`

**Comment by hydai** [comment]
Our macOS 13 aarch64 runner is down, and we are fixing it. You can just go ahead and leave it alone from now.

**Pull request merged**
