### PR TITLE
[plugin] Stable Diffusion: upgrade version to e71ddce

### PR DESCRIPTION
**Pull request by grorge123**
Implement #3701.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
@grorge123 
Is this ready for review?

**Comment by grorge123** [comment]
> @grorge123 Is this ready for review?

I am modifying Rust SDK to run the new version of API. It will done in these two days.

**Comment by hydai** [comment]
Got it. @q82419 Let's wait for this PR to have rc.4. Also, some bugs, such as the Ubuntu assets, need to be fixed before rc.4.

**Review by hydai — APPROVED** [review]

**Pull request merged**
