### PR TITLE
[WASI-NN] PyTorch Backend - Added support for Tuple Type Output Tensors 

### PR DESCRIPTION
**Pull request by sarrah-basta**
Add Support for Tuple Type Output Tensors for PyTorch.

## Environment
- Hardware Architecture: (x86\_64)
- Operating system: (Ubuntu 22.04)
- C++ Compiler version: gcc 11.3.0 cmake
- CMake version: 3.22.1
- CMake flags: -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="PyTorch"

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
Hi @sarrah-basta 
Please sign DCO in the commit message: https://www.secondstate.io/articles/dco/

**Review by hydai — CHANGES_REQUESTED** [review]
The DCO check failed

**Comment by hydai** [comment]
Ping @sarrah-basta

**Comment by sarrah-basta** [comment]
Hello @hydai 

Apologies for not being able to sign the DCO sooner.

I have signed the DCO and all checks except two have passed. Is there something needed from my end to rectify the failing checks, in Ubuntu 22.04 I can see that the build is passing but uploading to Code Coverage is failing, and the other one is failing build for nix, which I don't have any idea about. Please let me know if anything is required.

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Hi @sarrah-basta 
I found this PR only added the support for Tuple Type without updating the error messages in the fallback area: https://github.com/WasmEdge/WasmEdge/pull/2564/files#diff-a274d631f19fc70b99811841acff2de55b94d4abcb9d536a8f099bb796cfa82eL144-L145

Would you like to raise another PR for it?

**Comment by sarrah-basta** [comment]
> Hi @sarrah-basta I found this PR only added the support for Tuple Type without updating the error messages in the fallback area: https://github.com/WasmEdge/WasmEdge/pull/2564/files#diff-a274d631f19fc70b99811841acff2de55b94d4abcb9d536a8f099bb796cfa82eL144-L145
> 
> Would you like to raise another PR for it?

Yes apologies for forgetting to remove them. I'll open another PR and add you as a reviewer on it. 

Thank you !

**Comment by sarrah-basta** [comment]
@hydai I have created the new pull request here https://github.com/WasmEdge/WasmEdge/pull/2747 which can be merged once the checks pass.

**Pull request merged**
