### PR TITLE
[Utils] Installer and CI: fixes and improvements

### PR DESCRIPTION
**Pull request by SAtacker**
- CI should fail when a .bashrc is generated. Instead it reports both pass and fail and does not exit

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Review by hydai — DISMISSED** [review]
I also missed this ;-)
Nice catch.

**Comment by SAtacker** [comment]
It is still not reporting correct output.

**Comment by hydai** [comment]
Please remind me which one should fail.

**Comment by SAtacker** [comment]
> Please remind me which one should fail.

The condition `ls -a ~ | grep .bashrc && (echo "Fail: Bashrc found" && exit 1) || echo "Pass: Bashrc not found"` is incorrect.
We can see that even though it exits with 1 the `||` operator allows to run the second command. The operands are incorrect.
Out intended output should be correctly given by `ls -a ~ | grep .bashrc && (echo "Fail: Bashrc found" && exit 1 || echo "Pass: Bashrc not found")`

**Comment by SAtacker** [comment]
Thanks @q82419 for the reports,PTAL!

Testing:

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | INSTALL_PY_URL=https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_python_installer/utils/install.py bash -s -- -D --dist manylinux2014
```

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | INSTALL_PY_URL=https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_python_installer/utils/install.py bash -s -- -D --dist ubuntu20.04
```

**Comment by q82419** [comment]
> Thanks @q82419 for the reports,PTAL!
> 
> Testing:
> 
> ```
> curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | INSTALL_PY_URL=https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_python_installer/utils/install.py bash -s -- -D --dist manylinux2014
> ```
> 
> ```
> curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | INSTALL_PY_URL=https://raw.githubusercontent.com/SAtacker/WasmEdge/fix_python_installer/utils/install.py bash -s -- -D --dist ubuntu20.04
> ```

Seems like the behavior is correct.
Please help to check #2198 . Thanks.

**Comment by hydai** [comment]
Just want to know if we can continue to review this. Or does it need any update?

**Comment by SAtacker** [comment]
I think we should merge this ASAP. I'll make new PRs for the remaining issues.
The issues we'll be able to close are:

- https://github.com/WasmEdge/WasmEdge/issues/2187
- https://github.com/WasmEdge/WasmEdge/issues/2197

Remaining:
- https://github.com/WasmEdge/WasmEdge/issues/2201
- https://github.com/WasmEdge/WasmEdge/issues/2198
- https://github.com/WasmEdge/WasmEdge/issues/2196
- https://github.com/WasmEdge/WasmEdge/issues/2193

**Review by hydai — APPROVED** [review]
I am going to merge this once the CI is finished.

**Pull request merged**
