### PR TITLE
[Community] propose adding an additional code of conduct

### PR DESCRIPTION
**Pull request by alabulei1**
In this PR, I'd like to add guidelines for the use of other developers' open-source work in our contributor's code. 

Maintainers and Community members, please take a look and leave your comment. Thanks.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
The linter failed. Please format your markdown file.

**Comment by apepkuss** [comment]
LGTM

**Comment by gusye1234** [comment]
LGTM

**Comment by yanghaku** [comment]
LGTM

**Review by L-jasmine — APPROVED** [review]
LGTM

**Review by sonder-joker — APPROVED** [review]

**Comment by sonder-joker** [comment]
LGTM

**Comment by hangedfish** [comment]
LGTM

**Review by hydai — APPROVED** [review]

**Pull request merged**
