### PR TITLE
[docs] C++ sdk summary added

### PR DESCRIPTION
**Pull request by Vishvsalvi**

### CODE REVIEW

**Comment by Vishvsalvi** [comment]
Can I get some help to make sure these checks are successful

**Comment by hydai** [comment]
Hi @Vishvsalvi Please fix the lint issue first.

**Comment by Vishvsalvi** [comment]
> Hi @Vishvsalvi Please fix the lint issue first.

Sure

**Comment by Vishvsalvi** [comment]
@hydai I've fixed the lint issues

**Review by hydai — APPROVED** [review]
LGTM

**Pull request merged**
