### PR TITLE
Created Hindi translation of simd.md and SECURITY.md 

### PR DESCRIPTION
**Pull request by MaazKhan711635**
Added a translation of the file SECURITY.md to hindi in the doc folder.
Signed-off-by: Maaz Khan <maazkhan711635@gmail.com>

### CODE REVIEW

**Comment by hydai** [comment]
Hi @MaazKhan711635 
Thanks for your contribution.

I found these two files have different naming style. One is `hindi`, the other is `Hindi`. Could you please use `Hindi` in both filenames?

**Comment by MaazKhan711635** [comment]
Okay

**Comment by hydai** [comment]
I will squash your commits. Could you remove the `doc/simd-hindi-translation.md`?
Because here are `doc/simd-hindi-translation.md` and `doc/simd-Hindi-translation.md` which are the same content.

**Comment by MaazKhan711635** [comment]
Then please Remove my commits so I can commit again in proper way.
Parson my inexperience as this was my first time.

**Comment by hydai** [comment]
Because this is in your own branch, I cannot modify it directly.

If you are using command line, please try `git rm doc/simd-hindi-translation.md` and then git commit again to remove the file.

**Pull request closed without merging**
