### PR TITLE
feat: support GC proposal

### PR DESCRIPTION
**Pull request by little-willy**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by little-willy** [comment]
PR merged before it is ready for review yet?

**Comment by hydai** [comment]
Hi @little-willy 
Sorry, I didn't notice that this is still a draft. Do you still need to update anything?
We are merging it because this PR is still based on an old branch, and some codes may be incompatible with [the latest commits of the Typed function reference proposal](https://github.com/WasmEdge/WasmEdge/pull/2691). So we will do the rebase with that branch first.

**Comment by little-willy** [comment]
> Sorry, I didn't notice that this is still a draft. Do you still need to update anything?

Yes, the PR is still a draft. GC proposal is depending on the typed function reference proposal. Therefore, the current implementation of GC proposal is based on an earlier version of typed function reference proposal, which is before the later refactor on the typed function reference implementation, and I plan to later adapt the refactor on the current GC proposal implementation.

Could you reset the dev branch `proposal/gc` to the current `proposal/func-ref`? After that I will create another draft PR to merge the current GC implementation onto the `proposal/gc`, and then adapt the refactor to the GC implementation.

**Pull request merged**
