### PR TITLE
[Installer] feat: Support darwin x86_64 platform for the extensions.

### PR DESCRIPTION
**Pull request by SAtacker**
Reference - #1427

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by SAtacker** [comment]
Testing
```
curl -sSf https://raw.githubusercontent.com/SAtacker/WasmEdge/installer_darwin_x86/utils/install.sh | bash -s -- -v 0.10.0-alpha.1
```

**Comment by SAtacker** [comment]
@q82419 could you please test it?

**Comment by SAtacker** [comment]
> It seems like the symbolic link failed.
> 
> ```
> q82419@MacBook-Pro:~/proj $ ll ~/.wasmedge/lib/
> total 937864
> drwxr-xr-x  10 q82419  staff        320 May  6 22:57 ./
> drwxr-xr-x   6 q82419  staff        192 May  6 22:56 ../
> -r-xr-xr-x   1 q82419  staff  437807432 Jan  1  2000 libtensorflow.2.6.0.dylib*
> -r-xr-xr-x   1 q82419  staff   24038640 Jan  1  2000 libtensorflow_framework.2.6.0.dylib*
> -r-xr-xr-x   1 q82419  staff    3739240 May  4 15:06 libtensorflowlite_c.dylib*
> -rwxr-xr-x   1 q82419  staff     960648 May  6 21:04 libwasmedge-image_c.dylib*
> -rwxr-xr-x   1 q82419  staff     436248 May  6 21:58 libwasmedge-tensorflow_c.dylib*
> -rwxr-xr-x   1 q82419  staff     448256 May  6 21:58 libwasmedge-tensorflowlite_c.dylib*
> -rwxr-xr-x   1 q82419  staff    1960960 May  6 22:56 libwasmedge_c.dylib*
> drwxr-xr-x   3 q82419  staff         96 May  6 22:56 wasmedge/
> ```

Thanks for trying it out. I will take some time to install macOS virtual machine and fix it.

**Comment by q82419** [comment]
I think it's simple as on `linux`: use `ln -s` command.
Just need to take care about the symbolic link name as I mentioned in the issue.
You can keep testing and let me try then. Thanks.

**Comment by SAtacker** [comment]
> I think it's simple as on `linux`: use `ln -s` command. Just need to take care about the symbolic link name as I mentioned in the issue. You can keep testing and let me try then. Thanks.

A simple regex match issue as I had assumed it will be similar to Linux's `so.2.6.0` where is it is `2.6.0.dylib`

**Comment by SAtacker** [comment]
Could you please test @q82419 ?

**Comment by SAtacker** [comment]
The failing macOS CI test is related to https://github.community/t/unable-to-update-homebrews-git-on-macos-runner-without-removing-prebuilt-git-package/246983

**Comment by SAtacker** [comment]
Oops, too much force push, sorry!

**Comment by q82419** [comment]
I can install the `0.10.0-alpha.1` successfully on MacOS.
Another issue is that the version before `0.9.1` on MacOS have no extensions supporting.

```
q82419@MacBook-Pro:~/proj $ curl -sSf https://raw.githubusercontent.com/SAtacker/WasmEdge/installer_darwin_x86/utils/install.sh | bash -s -- -v 0.9.1 -e all
Detected Darwin-x86_64
cat: /Users/q82419/.bashrc: No such file or directory
No path provided
Installing in /Users/q82419/.wasmedge
WasmEdge Installation at /Users/q82419/.wasmedge
Fetching WasmEdge-0.9.1
/tmp/wasmedge.34473 ~/proj/WasmEdge
######################################################################## 100.0%
~/proj/WasmEdge
Installing WasmEdge-0.9.1-Darwin in /Users/q82419/.wasmedge/include
Installing WasmEdge-0.9.1-Darwin in /Users/q82419/.wasmedge/lib
Installing WasmEdge-0.9.1-Darwin in /Users/q82419/.wasmedge/bin
All extensions
Fetching WasmEdge-image-0.9.1
/tmp/wasmedge.34473 ~/proj/WasmEdge
##O=#  #
~/proj/WasmEdge

    Please see --help
    If issue perists make a trace using -V and submit it to
https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md
```

Maybe we should handle this case?

**Comment by SAtacker** [comment]
> I can install the `0.10.0-alpha.1` successfully on MacOS.
> Another issue is that the version before `0.9.1` on MacOS have no extensions supporting.
> 
> ```
> q82419@MacBook-Pro:~/proj $ curl -sSf https://raw.githubusercontent.com/SAtacker/WasmEdge/installer_darwin_x86/utils/install.sh | bash -s -- -v 0.9.1 -e all
> Detected Darwin-x86_64
> cat: /Users/q82419/.bashrc: No such file or directory
> No path provided
> Installing in /Users/q82419/.wasmedge
> WasmEdge Installation at /Users/q82419/.wasmedge
> Fetching WasmEdge-0.9.1
> /tmp/wasmedge.34473 ~/proj/WasmEdge
> ######################################################################## 100.0%
> ~/proj/WasmEdge
> Installing WasmEdge-0.9.1-Darwin in /Users/q82419/.wasmedge/include
> Installing WasmEdge-0.9.1-Darwin in /Users/q82419/.wasmedge/lib
> Installing WasmEdge-0.9.1-Darwin in /Users/q82419/.wasmedge/bin
> All extensions
> Fetching WasmEdge-image-0.9.1
> /tmp/wasmedge.34473 ~/proj/WasmEdge
> ##O=#  #
> ~/proj/WasmEdge
> 
>     Please see --help
>     If issue perists make a trace using -V and submit it to
> https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md
> ```
> 
> Maybe we should handle this case?

Yes, I thought so but I got tired yesterday late at night(technically early morning today) and slept. Exams are putting a lot of stress, let me work on it tonight.

**Comment by q82419** [comment]
It's OK, we are just in alpha stage now and still have time to finish it before the official release. Thanks.

**Comment by SAtacker** [comment]
I think it's done. Please check @q82419 
Thanks

**Comment by q82419** [comment]
It works well on `0.9.1` and `0.10.0-alpha.1`.
@hydai  can you help to check the `darwin M1`?
@SAtacker but the installer CI on MacOS failed. Can you help to fix it?
Thanks.

**Comment by SAtacker** [comment]
> The failing macOS CI test is related to https://github.community/t/unable-to-update-homebrews-git-on-macos-runner-without-removing-prebuilt-git-package/246983

Any other way of installing git?

**Comment by SAtacker** [comment]
Removing and then installing is one workaround.

**Comment by hydai** [comment]
> Removing and then installing is one workaround.

Is the git installed in the default image? If so and the version is new enough, maybe use it directly is fine. If not, then we can remove it first and then re-install from brew.

**Comment by hydai** [comment]
Hi @SAtacker Could you squash some of your commits? Say the revert part to make the commit history clean.

**Review by hydai — APPROVED** [review]
LGTM.

**Pull request merged**
