### PR TITLE
[Misc] Rename wasi_llm -> wasmedge_llmc

### PR DESCRIPTION
**Pull request by junaire**
Related to https://github.com/WasmEdge/WasmEdge/issues/3523#issuecomment-2300783746

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by q82419** [comment]
Hi @junaire ,

I've done the rename in #3685.
Please help to cherry-pick the changes into your PR, and I'll rebase on this. Thanks!

**Comment by junaire** [comment]
> Hi @junaire ,
> 
> I've done the rename in #3685. Please help to cherry-pick the changes into your PR, and I'll rebase on this. Thanks!

oh sorry, I overlooked your pr first, well if you're already working on this I think I can close this one, rebasing on these huge changes sounds pretty terrible...

**Comment by q82419** [comment]
@hydai  how do you think? I can separate another PR from the original one.

**Comment by hydai** [comment]
I didn't notice that @q82419 already had a commit for it. Let's use @q82419 one and close this.

**Pull request closed without merging**
