### PR TITLE
[Docs] add APISIX to list of proxy

### PR DESCRIPTION
**Pull request by spacewander**

### CODE REVIEW

**Comment by spacewander** [comment]
Hi, WasmEdge developers!

I am the core developer of [Apache APISIX](https://github.com/apache/apisix/) & [wasm-nginx-module](https://github.com/api7/wasm-nginx-module). I am willing to integrate WasmEdge into APISIX as a new VM of the wasm-nginx-module.

The wasm-nginx-module is the first open-source solution to run Wasm in Nginx. And Apache APISIX is one of the most famous API gateways in the world. It would be great if we can work together.

**Comment by juntao** [comment]
This is great! @spacewander  Thank you for reaching out! Let's use this PR to collaborate. Is there anything we need to do on WasmEdge's end to support APISIX and NGINX integration?

**Comment by spacewander** [comment]
After reading part of the doc, I have a question: what are the advantages of WasmEdge over wasmtime in the proxy, except performance? We already support wasmtime. If it would be great if we can benefit more by supporting WasmEdge.

**Comment by juntao** [comment]
I think there are several potential advantages beyond performance:

1 WasmEdge supports some non-standard but important extensions for cloud native environments. For example, it supports non blocking network sockets, WasmEdge-bindgen for complex para passing, and Tensorflow / AI inference. They may not be important for a proxy embedded runtime right now, but could expand the types of applications your developers might want to try. 

2 In a service mesh environment, the developer might want to use Wasm in both the proxy and the microservice. WasmEdge is the runtime that provides the best integration with various k8s distributions.

3 It is often a good idea to support multiple runtimes when you can because each project might have different roadmaps, adoption, and community. For example, WasmEdge is a CNCF project and it is working with a lot cloud native project. Other Wasm runtimes might be focused on the browser or IoT devices.

4 WasmEdge is written in C++, and hence has better (in our view) support for different OSes and language SDKs.

Hope that helps!

**Comment by spacewander** [comment]
Good.
I just add the WasmEdge support to our February plan: https://github.com/api7/wasm-nginx-module/issues/85

**Comment by alabulei1** [comment]
Hi, @spacewander I saw you have [integrated WasmEdge into APISIX](https://github.com/api7/wasm-nginx-module/pull/93 ). Much appreciated your work. I'm wondering if you are interested in adding docs for WasmEdge and APISIX. Let me know what you think. Thanks.

**Comment by spacewander** [comment]
@alabulei1 
Actually, I have not integrated it into APISIX yet. wasm-nginx-module supports WasmEdge but APISIX doesn't enable this feature yet.
I have a plan to support it in APISIX but this plan is still on my long task queue due to some high-priority tasks.
Maybe you can open an issue or start a discussion in the mail list of APISIX so that we can push this forward。

**Comment by alabulei1** [comment]
> @alabulei1 Actually, I have not integrated it into APISIX yet. wasm-nginx-module supports WasmEdge but APISIX doesn't enable this feature yet. I have a plan to support it in APISIX but this plan is still on my long task queue due to some high-priority tasks. Maybe you can open an issue or start a discussion in the mail list of APISIX so that we can push this forward。

Hi, @spacewander Sorry for my misunderstanding. Yeah. Let's do it. I will raise an issue later. May I invite you to write an article for the wasm-nginx-module support? We could promote together. Thanks.

**Comment by spacewander** [comment]
> May I invite you to write an article for the wasm-nginx-module support?

Where should I put the doc? The wasm-nginx-module is a library (or you can call it a script engine embedded in Nginx).

**Comment by alabulei1** [comment]
> Where should I put the doc? The wasm-nginx-module is a library (or you can call it a script engine embedded in Nginx).

Hi, @spacewander I think we could put this article in the [Service Mesh & Runtime](https://wasmedge.org/book/en/frameworks/mesh.html) Section. What do you think?

**Comment by spacewander** [comment]
OK, I will do it this weekend.

**Comment by q82419** [comment]
Out-of-date and replaced by #1569.

**Pull request closed without merging**
