### PR TITLE
[Misc] Fix fdReaddir on large numbers of entries

### LINKED ISSUE #1711: Directories with more than ~150 files are truncated when mapped ?
## Steps o reproduce

This is related to https://github.com/bytecodealliance/wasmtime/issues/2493
Compile the C program into wasm : 
[ls.txt](https://github.com/WasmEdge/WasmEdge/files/9233791/ls.txt)

(1) `wasmedge ls.wasm --dir=./testfolder -- testfolder | wc -l`
or 
(2)`wasmedgec ls.wasm ls.so` and 
`wasmedge ls.so --dir=./testfolder -- testfolder | wc -l`

## Expected result
203

## Autual result
0

## Environment
wasmedge 0.9.1
The problem both occur on macOS and ubuntu.

### PR DESCRIPTION
**Pull request by LFsWang**
Fix #1711

The definition of arguments for `fdReaddir` are too ambiguous, I am not sure the excepted behavior.

some discussion: https://github.com/WebAssembly/wasi-filesystem/issues/3
definition: https://docs.rs/wasi/0.9.0+wasi-snapshot-preview1/wasi/fn.fd_readdir.html

Signed-off-by: LFsWang <tnst92002@gmail.com>

### CODE REVIEW

**Comment by hydai** [comment]
Hi @LFsWang 
Is it possible to include the test cases in the unit tests?

**Comment by hydai** [comment]
Hi @harry900831 
Please check if this PR also fixes #2123

**Review by hydai — APPROVED** [review]
LGTM

**Comment by harry900831** [comment]
IINW, It seems that there's still a problem on macOS.

I tried to reproduce #2123 after applying this change, and it seems that it still can't list all the files correctly.

Screenshot 2022-12-22 at 02 09 30

**Comment by hydai** [comment]
Hi @harry900831 
Can you take over this to make it fixed before the 0.12 release?

@LFsWang is out of the office for a short period.

**Comment by harry900831** [comment]
OK

**Comment by hydai** [comment]
This is replaced by #2296

**Pull request closed without merging**
