### PR TITLE
[Chore] - Removed `zh-tw`  Docs

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

According to @alabulei1 's suggestion, this PR removes `zh-tw` docs as we do not have much content for the same.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
Hi @adithyaakrishna,

Thanks for the contribution.

Let's keep the `README-zh-tw.md`, which is useful. Thanks.

**Comment by adithyaakrishna** [comment]
@alabulei1 Done, updated the Readme now :)

**Review by hydai — APPROVED** [review]
LGTM

**Pull request merged**
