### PR TITLE
[CI] move wasi-nn neuralspeed backend to the last target to avoid failing others

### PR DESCRIPTION
**Pull request by hydai**
Because the WASI-NN Neural Speed CI has a random segfault, it will block other backends. As a workaround, make it the last target.
This will be resolved after #3596 is fixed.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by 0yi0** [comment]
CI failed on pytorch, is that expected?

**Comment by hydai** [comment]
> CI failed on pytorch, is that expected?

It failed on Neural Speed.

```
[2024-07-26 00:09:28.895] [info] [WASI-NN] Neural speed: BinModel: 1736875520
/__w/_temp/8585c7f3-3a21-4231-8c09-75a21b685e7a.sh: line 20:  9814 Segmentation fault      (core dumped) ./${test_bin}
```

**Review by 0yi0 — APPROVED** [review]
Oh I got it

**Comment by hydai** [comment]
The previous blocker is resolved. Closing this.

**Pull request closed without merging**
