### PR TITLE
[Plugin] Fix StableDiffusion plugin on MacOS.

### PR DESCRIPTION
**Pull request by q82419**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
@q82419 
Looks like Intel MacOS failed.

**Comment by hydai** [comment]
Hi @q82419 
If the only failed CI is on the Intel macOS, we can leave an issue and move forward with releasing the RC. We don't need to be blocked by a specific target.

**Comment by q82419** [comment]
It seems like the `cblas_sgemm` needs MacOS 13.4 when acceleration enabled.
I'll disable acceleration before 13.4 and test again.

**Review by dm4 — APPROVED** [review]

**Pull request merged**
