### PR TITLE
fix function params in plugin/get-string/getstring.cpp

### PR DESCRIPTION
**Pull request by edwardramsey**
fix compile error for plugin/get-string/getstring.cpp

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by hydai — APPROVED** [review]
Nice catch. Thanks

**Review by hydai — CHANGES_REQUESTED** [review]
Could you please fix the lint issue before we get this merged?

**Comment by edwardramsey** [comment]
OK, I have already update code.

**Review by hydai — APPROVED** [review]

**Pull request merged**
