### PR TITLE
[MISC] Fix default plugin paths

### PR DESCRIPTION
**Pull request by harry900831**
Signed-off-by: Harry Chiang <harry900831@gmail.com>

### CODE REVIEW

**Comment by harry900831** [comment]
I follow the Build WasmEdge from https://wasmedge.org/book/en/contribute/build_from_src/macos.html, the tree is as follow:

build/
|-- lib
|   |-- api
|   |  |-- libwasmedge.so -> libwasmedge.so.0
|   |  |-- libwasmedge.so.0 -> libwasmedge.so.0.0.1
`-- plugins
    |-- wasmedge_wasiNN
    |  |-- libwasmedgePluginWasiNN.so
    |-- wasmedge_process
    |  |-- libwasmedgeprocess.so

**Comment by q82419** [comment]
> I follow the Build WasmEdge from https://wasmedge.org/book/en/contribute/build_from_src/macos.html, the tree is as follow:
> 
> build/ |-- lib | |-- api | | |-- libwasmedge.so -> libwasmedge.so.0 | | |-- libwasmedge.so.0 -> libwasmedge.so.0.0.1 `-- plugins |-- wasmedge_wasiNN | |-- libwasmedgePluginWasiNN.so |-- wasmedge_process | |-- libwasmedgeprocess.so

Its the build tree, you should install it.
If you modify the code as this PR, the installer case will fail.

**Comment by q82419** [comment]
You can refer to the build command here:

https://wasmedge.org/book/en/contribute/build_from_src/plugin_wasi_nn.html

You should install the build to put the plug-in into the correct path, or set the `WASMEDGE_PLUGIN_PATH`.

**Comment by harry900831** [comment]
Aha, I found my mistake...
I've tried cmake --install after cmake --build before, and the path still wrong... that's because I'm still using the build/tools/wasmedge/wasmedge so I thought this part is incorrect.

Thanks!

**Pull request closed without merging**
