### PR TITLE
[CI] Refactor the release workflows

### PR DESCRIPTION
**Pull request by apepkuss**
In this PR, the release workflows for `wasmedge-macro` and `wasmedge-types` are updated.

### CODE REVIEW

**Review by hydai — DISMISSED** [review]

**Comment by hydai** [comment]
Hi @apepkuss 
Why do you roll back the cargo-smart-release? IIRC, we change it just a few weeks ago.

**Comment by apepkuss** [comment]
> Hi @apepkuss Why do you roll back the cargo-smart-release? IIRC, we change it just a few weeks ago.

@hydai The motivation for using `cargo-smart-release` is that it can (1) make tags automatically and (2) automate the changelog generation. However, in the recent two releases, we found that (1) it is not allowed to tag a release automatically, (2) the tag cannot be customized, and (3) the contents of the CHANGELOG generated do not satisfy our requirements. In addition, `cargo publish` is documented better and much more lightweight than `cargo-smart-release`. Based on the reasons above we believe that `cargo publish` is a better choice for our current requirements. Thanks!

**Review by hydai — APPROVED** [review]
LGTM

**Comment by apepkuss** [comment]
@hydai Thanks for the review!

**Pull request merged**
