### PR TITLE
Install into User's Home by default #381 

### PR DESCRIPTION
**Pull request by SAtacker**
* Checks if script is being run with `root` permissions
* Installs into current users home directory
* When run by `root` Checks if `sudo` is present and installs into current user's home directory
* If `sudo` is absent it does not manipulate $HOME

Ref - #381

### CODE REVIEW

**Comment by SAtacker** [comment]
Let me pull some changes over this too

**Comment by SAtacker** [comment]
Should now be able to fix #382

**Comment by juntao** [comment]
I am seeing this error when running `./install.sh -e all`

```
Fetching WasmEdge-tensorflow-tools-0.8.2
WasmEdge-tensorflow 100%[===================>]  28.20M  46.0MB/s    in 0.6s
/root/.wasmedge/bin/wasmedge-tensorflow: error while loading shared libraries: libtensorflow.so.2: cannot open shared object file: No such file or directory
./install.sh: line 214: [: =: unary operator expected
version 0.8.2 does not match  for wasmedge-tensorflow-0.8.2
```

**Comment by SAtacker** [comment]
Thanks for this @juntao . I just needed to add `$IPATH/lib` to `ldconfig`

**Review by juntao — APPROVED** [review]
I tested and it works now. Thanks.

**Pull request merged**
