### PR TITLE
[CI] Enable nix log when building process failed

### PR DESCRIPTION
**Pull request by hydai**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
Looks like the `--log-lines` option won't help showing the failure logs.

**Comment by dannypsnl** [comment]
image


I think `-L` is for stderr output

**Comment by dannypsnl** [comment]
`-L` result:
image

**Review by dannypsnl — APPROVED** [review]

**Pull request merged**
